// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: git/git.proto

package gitv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	common "github.com/uniedit/server/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_git_git_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Repo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	RepoType      string                 `protobuf:"bytes,5,opt,name=repo_type,json=repoType,proto3" json:"repo_type,omitempty"`
	Visibility    string                 `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,8,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,9,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	LfsEnabled    bool                   `protobuf:"varint,10,opt,name=lfs_enabled,json=lfsEnabled,proto3" json:"lfs_enabled,omitempty"`
	LfsSizeBytes  int64                  `protobuf:"varint,11,opt,name=lfs_size_bytes,json=lfsSizeBytes,proto3" json:"lfs_size_bytes,omitempty"`
	TotalSize     int64                  `protobuf:"varint,12,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	StarsCount    int32                  `protobuf:"varint,13,opt,name=stars_count,json=starsCount,proto3" json:"stars_count,omitempty"`
	ForksCount    int32                  `protobuf:"varint,14,opt,name=forks_count,json=forksCount,proto3" json:"forks_count,omitempty"`
	CloneUrl      string                 `protobuf:"bytes,15,opt,name=clone_url,json=cloneUrl,proto3" json:"clone_url,omitempty"`
	LfsUrl        string                 `protobuf:"bytes,16,opt,name=lfs_url,json=lfsUrl,proto3" json:"lfs_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_git_git_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{1}
}

func (x *Repo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Repo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Repo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Repo) GetRepoType() string {
	if x != nil {
		return x.RepoType
	}
	return ""
}

func (x *Repo) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Repo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repo) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *Repo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Repo) GetLfsEnabled() bool {
	if x != nil {
		return x.LfsEnabled
	}
	return false
}

func (x *Repo) GetLfsSizeBytes() int64 {
	if x != nil {
		return x.LfsSizeBytes
	}
	return 0
}

func (x *Repo) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *Repo) GetStarsCount() int32 {
	if x != nil {
		return x.StarsCount
	}
	return 0
}

func (x *Repo) GetForksCount() int32 {
	if x != nil {
		return x.ForksCount
	}
	return 0
}

func (x *Repo) GetCloneUrl() string {
	if x != nil {
		return x.CloneUrl
	}
	return ""
}

func (x *Repo) GetLfsUrl() string {
	if x != nil {
		return x.LfsUrl
	}
	return ""
}

type CreateRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Visibility    string                 `protobuf:"bytes,3,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	LfsEnabled    bool                   `protobuf:"varint,5,opt,name=lfs_enabled,json=lfsEnabled,proto3" json:"lfs_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRepoRequest) Reset() {
	*x = CreateRepoRequest{}
	mi := &file_git_git_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepoRequest) ProtoMessage() {}

func (x *CreateRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepoRequest.ProtoReflect.Descriptor instead.
func (*CreateRepoRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRepoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRepoRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateRepoRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *CreateRepoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRepoRequest) GetLfsEnabled() bool {
	if x != nil {
		return x.LfsEnabled
	}
	return false
}

type UpdateRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *common.StringValue    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *common.StringValue    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    *common.StringValue    `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	DefaultBranch *common.StringValue    `protobuf:"bytes,5,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	LfsEnabled    *common.BoolValue      `protobuf:"bytes,6,opt,name=lfs_enabled,json=lfsEnabled,proto3" json:"lfs_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepoRequest) Reset() {
	*x = UpdateRepoRequest{}
	mi := &file_git_git_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepoRequest) ProtoMessage() {}

func (x *UpdateRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepoRequest.ProtoReflect.Descriptor instead.
func (*UpdateRepoRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRepoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRepoRequest) GetName() *common.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateRepoRequest) GetDescription() *common.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateRepoRequest) GetVisibility() *common.StringValue {
	if x != nil {
		return x.Visibility
	}
	return nil
}

func (x *UpdateRepoRequest) GetDefaultBranch() *common.StringValue {
	if x != nil {
		return x.DefaultBranch
	}
	return nil
}

func (x *UpdateRepoRequest) GetLfsEnabled() *common.BoolValue {
	if x != nil {
		return x.LfsEnabled
	}
	return nil
}

type ListReposRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Visibility    string                 `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposRequest) Reset() {
	*x = ListReposRequest{}
	mi := &file_git_git_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposRequest) ProtoMessage() {}

func (x *ListReposRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposRequest.ProtoReflect.Descriptor instead.
func (*ListReposRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{4}
}

func (x *ListReposRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListReposRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ListReposRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListReposRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReposRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReposResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repos         []*Repo                `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReposResponse) Reset() {
	*x = ListReposResponse{}
	mi := &file_git_git_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReposResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReposResponse) ProtoMessage() {}

func (x *ListReposResponse) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReposResponse.ProtoReflect.Descriptor instead.
func (*ListReposResponse) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{5}
}

func (x *ListReposResponse) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

func (x *ListReposResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListReposResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReposResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type StorageStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepoSizeBytes  int64                  `protobuf:"varint,1,opt,name=repo_size_bytes,json=repoSizeBytes,proto3" json:"repo_size_bytes,omitempty"`
	LfsSizeBytes   int64                  `protobuf:"varint,2,opt,name=lfs_size_bytes,json=lfsSizeBytes,proto3" json:"lfs_size_bytes,omitempty"`
	TotalSizeBytes int64                  `protobuf:"varint,3,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	LfsObjectCount int32                  `protobuf:"varint,4,opt,name=lfs_object_count,json=lfsObjectCount,proto3" json:"lfs_object_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StorageStats) Reset() {
	*x = StorageStats{}
	mi := &file_git_git_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStats) ProtoMessage() {}

func (x *StorageStats) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStats.ProtoReflect.Descriptor instead.
func (*StorageStats) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{6}
}

func (x *StorageStats) GetRepoSizeBytes() int64 {
	if x != nil {
		return x.RepoSizeBytes
	}
	return 0
}

func (x *StorageStats) GetLfsSizeBytes() int64 {
	if x != nil {
		return x.LfsSizeBytes
	}
	return 0
}

func (x *StorageStats) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *StorageStats) GetLfsObjectCount() int32 {
	if x != nil {
		return x.LfsObjectCount
	}
	return 0
}

type Collaborator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoId        string                 `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collaborator) Reset() {
	*x = Collaborator{}
	mi := &file_git_git_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collaborator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collaborator) ProtoMessage() {}

func (x *Collaborator) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collaborator.ProtoReflect.Descriptor instead.
func (*Collaborator) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{7}
}

func (x *Collaborator) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *Collaborator) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Collaborator) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *Collaborator) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AddCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCollaboratorRequest) Reset() {
	*x = AddCollaboratorRequest{}
	mi := &file_git_git_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollaboratorRequest) ProtoMessage() {}

func (x *AddCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*AddCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{8}
}

func (x *AddCollaboratorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddCollaboratorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCollaboratorRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type ListCollaboratorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collaborators []*Collaborator        `protobuf:"bytes,1,rep,name=collaborators,proto3" json:"collaborators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollaboratorsResponse) Reset() {
	*x = ListCollaboratorsResponse{}
	mi := &file_git_git_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollaboratorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollaboratorsResponse) ProtoMessage() {}

func (x *ListCollaboratorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollaboratorsResponse.ProtoReflect.Descriptor instead.
func (*ListCollaboratorsResponse) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{9}
}

func (x *ListCollaboratorsResponse) GetCollaborators() []*Collaborator {
	if x != nil {
		return x.Collaborators
	}
	return nil
}

type UpdateCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollaboratorRequest) Reset() {
	*x = UpdateCollaboratorRequest{}
	mi := &file_git_git_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollaboratorRequest) ProtoMessage() {}

func (x *UpdateCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCollaboratorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCollaboratorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCollaboratorRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type RemoveCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCollaboratorRequest) Reset() {
	*x = RemoveCollaboratorRequest{}
	mi := &file_git_git_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollaboratorRequest) ProtoMessage() {}

func (x *RemoveCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*RemoveCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveCollaboratorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveCollaboratorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoId        string                 `protobuf:"bytes,2,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Number        int32                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	SourceBranch  string                 `protobuf:"bytes,6,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`
	TargetBranch  string                 `protobuf:"bytes,7,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	AuthorId      string                 `protobuf:"bytes,9,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	MergedBy      string                 `protobuf:"bytes,10,opt,name=merged_by,json=mergedBy,proto3" json:"merged_by,omitempty"`
	MergedAt      string                 `protobuf:"bytes,11,opt,name=merged_at,json=mergedAt,proto3" json:"merged_at,omitempty"`
	ClosedAt      string                 `protobuf:"bytes,12,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_git_git_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{12}
}

func (x *PullRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PullRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *PullRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PullRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PullRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PullRequest) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

func (x *PullRequest) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *PullRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PullRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *PullRequest) GetMergedBy() string {
	if x != nil {
		return x.MergedBy
	}
	return ""
}

func (x *PullRequest) GetMergedAt() string {
	if x != nil {
		return x.MergedAt
	}
	return ""
}

func (x *PullRequest) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

func (x *PullRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PullRequest) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreatePRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SourceBranch  string                 `protobuf:"bytes,4,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`
	TargetBranch  string                 `protobuf:"bytes,5,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePRRequest) Reset() {
	*x = CreatePRRequest{}
	mi := &file_git_git_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePRRequest) ProtoMessage() {}

func (x *CreatePRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePRRequest.ProtoReflect.Descriptor instead.
func (*CreatePRRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePRRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePRRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePRRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePRRequest) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

func (x *CreatePRRequest) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

type ListPRsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPRsRequest) Reset() {
	*x = ListPRsRequest{}
	mi := &file_git_git_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPRsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPRsRequest) ProtoMessage() {}

func (x *ListPRsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPRsRequest.ProtoReflect.Descriptor instead.
func (*ListPRsRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{14}
}

func (x *ListPRsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListPRsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListPRsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPRsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPRsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PullRequests  []*PullRequest         `protobuf:"bytes,1,rep,name=pull_requests,json=pullRequests,proto3" json:"pull_requests,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPRsResponse) Reset() {
	*x = ListPRsResponse{}
	mi := &file_git_git_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPRsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPRsResponse) ProtoMessage() {}

func (x *ListPRsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPRsResponse.ProtoReflect.Descriptor instead.
func (*ListPRsResponse) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{15}
}

func (x *ListPRsResponse) GetPullRequests() []*PullRequest {
	if x != nil {
		return x.PullRequests
	}
	return nil
}

func (x *ListPRsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetPRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPRRequest) Reset() {
	*x = GetPRRequest{}
	mi := &file_git_git_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPRRequest) ProtoMessage() {}

func (x *GetPRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPRRequest.ProtoReflect.Descriptor instead.
func (*GetPRRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{16}
}

func (x *GetPRRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPRRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type UpdatePRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Title         *common.StringValue    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   *common.StringValue    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        *common.StringValue    `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePRRequest) Reset() {
	*x = UpdatePRRequest{}
	mi := &file_git_git_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePRRequest) ProtoMessage() {}

func (x *UpdatePRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_git_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePRRequest.ProtoReflect.Descriptor instead.
func (*UpdatePRRequest) Descriptor() ([]byte, []int) {
	return file_git_git_proto_rawDescGZIP(), []int{17}
}

func (x *UpdatePRRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePRRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *UpdatePRRequest) GetTitle() *common.StringValue {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *UpdatePRRequest) GetDescription() *common.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdatePRRequest) GetStatus() *common.StringValue {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_git_git_proto protoreflect.FileDescriptor

const file_git_git_proto_rawDesc = "" +
	"\n" +
	"\rgit/git.proto\x12\x0euniedit.git.v1\x1a\x13common/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdc\x03\n" +
	"\x04Repo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x1b\n" +
	"\trepo_type\x18\x05 \x01(\tR\brepoType\x12\x1e\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tR\n" +
	"visibility\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12%\n" +
	"\x0edefault_branch\x18\b \x01(\tR\rdefaultBranch\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\t \x01(\x03R\tsizeBytes\x12\x1f\n" +
	"\vlfs_enabled\x18\n" +
	" \x01(\bR\n" +
	"lfsEnabled\x12$\n" +
	"\x0elfs_size_bytes\x18\v \x01(\x03R\flfsSizeBytes\x12\x1d\n" +
	"\n" +
	"total_size\x18\f \x01(\x03R\ttotalSize\x12\x1f\n" +
	"\vstars_count\x18\r \x01(\x05R\n" +
	"starsCount\x12\x1f\n" +
	"\vforks_count\x18\x0e \x01(\x05R\n" +
	"forksCount\x12\x1b\n" +
	"\tclone_url\x18\x0f \x01(\tR\bcloneUrl\x12\x17\n" +
	"\alfs_url\x18\x10 \x01(\tR\x06lfsUrl\"\x9e\x01\n" +
	"\x11CreateRepoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"visibility\x18\x03 \x01(\tR\n" +
	"visibility\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vlfs_enabled\x18\x05 \x01(\bR\n" +
	"lfsEnabled\"\xdf\x02\n" +
	"\x11UpdateRepoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x04name\x18\x02 \x01(\v2\x1e.uniedit.common.v1.StringValueR\x04name\x12@\n" +
	"\vdescription\x18\x03 \x01(\v2\x1e.uniedit.common.v1.StringValueR\vdescription\x12>\n" +
	"\n" +
	"visibility\x18\x04 \x01(\v2\x1e.uniedit.common.v1.StringValueR\n" +
	"visibility\x12E\n" +
	"\x0edefault_branch\x18\x05 \x01(\v2\x1e.uniedit.common.v1.StringValueR\rdefaultBranch\x12=\n" +
	"\vlfs_enabled\x18\x06 \x01(\v2\x1c.uniedit.common.v1.BoolValueR\n" +
	"lfsEnabled\"\x8f\x01\n" +
	"\x10ListReposRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"visibility\x18\x02 \x01(\tR\n" +
	"visibility\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\x91\x01\n" +
	"\x11ListReposResponse\x12*\n" +
	"\x05repos\x18\x01 \x03(\v2\x14.uniedit.git.v1.RepoR\x05repos\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xb0\x01\n" +
	"\fStorageStats\x12&\n" +
	"\x0frepo_size_bytes\x18\x01 \x01(\x03R\rrepoSizeBytes\x12$\n" +
	"\x0elfs_size_bytes\x18\x02 \x01(\x03R\flfsSizeBytes\x12(\n" +
	"\x10total_size_bytes\x18\x03 \x01(\x03R\x0etotalSizeBytes\x12(\n" +
	"\x10lfs_object_count\x18\x04 \x01(\x05R\x0elfsObjectCount\"\x7f\n" +
	"\fCollaborator\x12\x17\n" +
	"\arepo_id\x18\x01 \x01(\tR\x06repoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"a\n" +
	"\x16AddCollaboratorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\"_\n" +
	"\x19ListCollaboratorsResponse\x12B\n" +
	"\rcollaborators\x18\x01 \x03(\v2\x1c.uniedit.git.v1.CollaboratorR\rcollaborators\"d\n" +
	"\x19UpdateCollaboratorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\"D\n" +
	"\x19RemoveCollaboratorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x9a\x03\n" +
	"\vPullRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\arepo_id\x18\x02 \x01(\tR\x06repoId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12#\n" +
	"\rsource_branch\x18\x06 \x01(\tR\fsourceBranch\x12#\n" +
	"\rtarget_branch\x18\a \x01(\tR\ftargetBranch\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1b\n" +
	"\tauthor_id\x18\t \x01(\tR\bauthorId\x12\x1b\n" +
	"\tmerged_by\x18\n" +
	" \x01(\tR\bmergedBy\x12\x1b\n" +
	"\tmerged_at\x18\v \x01(\tR\bmergedAt\x12\x1b\n" +
	"\tclosed_at\x18\f \x01(\tR\bclosedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\xa3\x01\n" +
	"\x0fCreatePRRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rsource_branch\x18\x04 \x01(\tR\fsourceBranch\x12#\n" +
	"\rtarget_branch\x18\x05 \x01(\tR\ftargetBranch\"f\n" +
	"\x0eListPRsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"t\n" +
	"\x0fListPRsResponse\x12@\n" +
	"\rpull_requests\x18\x01 \x03(\v2\x1b.uniedit.git.v1.PullRequestR\fpullRequests\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"6\n" +
	"\fGetPRRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\"\xe9\x01\n" +
	"\x0fUpdatePRRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x124\n" +
	"\x05title\x18\x03 \x01(\v2\x1e.uniedit.common.v1.StringValueR\x05title\x12@\n" +
	"\vdescription\x18\x04 \x01(\v2\x1e.uniedit.common.v1.StringValueR\vdescription\x126\n" +
	"\x06status\x18\x05 \x01(\v2\x1e.uniedit.common.v1.StringValueR\x06status2\xf4\f\n" +
	"\n" +
	"GitService\x12X\n" +
	"\n" +
	"CreateRepo\x12!.uniedit.git.v1.CreateRepoRequest\x1a\x14.uniedit.git.v1.Repo\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/repos\x12`\n" +
	"\tListRepos\x12 .uniedit.git.v1.ListReposRequest\x1a!.uniedit.git.v1.ListReposResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/repos\x12T\n" +
	"\aGetRepo\x12\x1e.uniedit.git.v1.GetByIDRequest\x1a\x14.uniedit.git.v1.Repo\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/repos/{id}\x12]\n" +
	"\n" +
	"UpdateRepo\x12!.uniedit.git.v1.UpdateRepoRequest\x1a\x14.uniedit.git.v1.Repo\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/repos/{id}\x12[\n" +
	"\n" +
	"DeleteRepo\x12\x1e.uniedit.git.v1.GetByIDRequest\x1a\x18.uniedit.common.v1.Empty\"\x13\x82\xd3\xe4\x93\x02\r*\v/repos/{id}\x12l\n" +
	"\x0fGetStorageStats\x12\x1e.uniedit.git.v1.GetByIDRequest\x1a\x1c.uniedit.git.v1.StorageStats\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/repos/{id}/storage\x12y\n" +
	"\x0fAddCollaborator\x12&.uniedit.git.v1.AddCollaboratorRequest\x1a\x18.uniedit.common.v1.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/repos/{id}/collaborators\x12\x81\x01\n" +
	"\x11ListCollaborators\x12\x1e.uniedit.git.v1.GetByIDRequest\x1a).uniedit.git.v1.ListCollaboratorsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/repos/{id}/collaborators\x12\x89\x01\n" +
	"\x12UpdateCollaborator\x12).uniedit.git.v1.UpdateCollaboratorRequest\x1a\x18.uniedit.common.v1.Empty\".\x82\xd3\xe4\x93\x02(:\x01*\x1a#/repos/{id}/collaborators/{user_id}\x12\x86\x01\n" +
	"\x12RemoveCollaborator\x12).uniedit.git.v1.RemoveCollaboratorRequest\x1a\x18.uniedit.common.v1.Empty\"+\x82\xd3\xe4\x93\x02%*#/repos/{id}/collaborators/{user_id}\x12f\n" +
	"\bCreatePR\x12\x1f.uniedit.git.v1.CreatePRRequest\x1a\x1b.uniedit.git.v1.PullRequest\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/repos/{id}/pulls\x12e\n" +
	"\aListPRs\x12\x1e.uniedit.git.v1.ListPRsRequest\x1a\x1f.uniedit.git.v1.ListPRsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/repos/{id}/pulls\x12f\n" +
	"\x05GetPR\x12\x1c.uniedit.git.v1.GetPRRequest\x1a\x1b.uniedit.git.v1.PullRequest\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/repos/{id}/pulls/{number}\x12o\n" +
	"\bUpdatePR\x12\x1f.uniedit.git.v1.UpdatePRRequest\x1a\x1b.uniedit.git.v1.PullRequest\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/repos/{id}/pulls/{number}\x12n\n" +
	"\aMergePR\x12\x1c.uniedit.git.v1.GetPRRequest\x1a\x1b.uniedit.git.v1.PullRequest\"(\x82\xd3\xe4\x93\x02\"\" /repos/{id}/pulls/{number}/merge2\x81\x01\n" +
	"\x10GitPublicService\x12m\n" +
	"\x0fListPublicRepos\x12 .uniedit.git.v1.ListReposRequest\x1a!.uniedit.git.v1.ListReposResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/repos/publicB\x96\x01\x92Ag\x12I\n" +
	"\vUniEdit API\x126UniEdit 后端 API（由 proto 自动生成 OpenAPI）2\x02v1\x1a\x0elocalhost:8080\"\a/api/v1*\x01\x01Z*github.com/uniedit/server/api/pb/git;gitv1b\x06proto3"

var (
	file_git_git_proto_rawDescOnce sync.Once
	file_git_git_proto_rawDescData []byte
)

func file_git_git_proto_rawDescGZIP() []byte {
	file_git_git_proto_rawDescOnce.Do(func() {
		file_git_git_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_git_git_proto_rawDesc), len(file_git_git_proto_rawDesc)))
	})
	return file_git_git_proto_rawDescData
}

var file_git_git_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_git_git_proto_goTypes = []any{
	(*GetByIDRequest)(nil),            // 0: uniedit.git.v1.GetByIDRequest
	(*Repo)(nil),                      // 1: uniedit.git.v1.Repo
	(*CreateRepoRequest)(nil),         // 2: uniedit.git.v1.CreateRepoRequest
	(*UpdateRepoRequest)(nil),         // 3: uniedit.git.v1.UpdateRepoRequest
	(*ListReposRequest)(nil),          // 4: uniedit.git.v1.ListReposRequest
	(*ListReposResponse)(nil),         // 5: uniedit.git.v1.ListReposResponse
	(*StorageStats)(nil),              // 6: uniedit.git.v1.StorageStats
	(*Collaborator)(nil),              // 7: uniedit.git.v1.Collaborator
	(*AddCollaboratorRequest)(nil),    // 8: uniedit.git.v1.AddCollaboratorRequest
	(*ListCollaboratorsResponse)(nil), // 9: uniedit.git.v1.ListCollaboratorsResponse
	(*UpdateCollaboratorRequest)(nil), // 10: uniedit.git.v1.UpdateCollaboratorRequest
	(*RemoveCollaboratorRequest)(nil), // 11: uniedit.git.v1.RemoveCollaboratorRequest
	(*PullRequest)(nil),               // 12: uniedit.git.v1.PullRequest
	(*CreatePRRequest)(nil),           // 13: uniedit.git.v1.CreatePRRequest
	(*ListPRsRequest)(nil),            // 14: uniedit.git.v1.ListPRsRequest
	(*ListPRsResponse)(nil),           // 15: uniedit.git.v1.ListPRsResponse
	(*GetPRRequest)(nil),              // 16: uniedit.git.v1.GetPRRequest
	(*UpdatePRRequest)(nil),           // 17: uniedit.git.v1.UpdatePRRequest
	(*common.StringValue)(nil),        // 18: uniedit.common.v1.StringValue
	(*common.BoolValue)(nil),          // 19: uniedit.common.v1.BoolValue
	(*common.Empty)(nil),              // 20: uniedit.common.v1.Empty
}
var file_git_git_proto_depIdxs = []int32{
	18, // 0: uniedit.git.v1.UpdateRepoRequest.name:type_name -> uniedit.common.v1.StringValue
	18, // 1: uniedit.git.v1.UpdateRepoRequest.description:type_name -> uniedit.common.v1.StringValue
	18, // 2: uniedit.git.v1.UpdateRepoRequest.visibility:type_name -> uniedit.common.v1.StringValue
	18, // 3: uniedit.git.v1.UpdateRepoRequest.default_branch:type_name -> uniedit.common.v1.StringValue
	19, // 4: uniedit.git.v1.UpdateRepoRequest.lfs_enabled:type_name -> uniedit.common.v1.BoolValue
	1,  // 5: uniedit.git.v1.ListReposResponse.repos:type_name -> uniedit.git.v1.Repo
	7,  // 6: uniedit.git.v1.ListCollaboratorsResponse.collaborators:type_name -> uniedit.git.v1.Collaborator
	12, // 7: uniedit.git.v1.ListPRsResponse.pull_requests:type_name -> uniedit.git.v1.PullRequest
	18, // 8: uniedit.git.v1.UpdatePRRequest.title:type_name -> uniedit.common.v1.StringValue
	18, // 9: uniedit.git.v1.UpdatePRRequest.description:type_name -> uniedit.common.v1.StringValue
	18, // 10: uniedit.git.v1.UpdatePRRequest.status:type_name -> uniedit.common.v1.StringValue
	2,  // 11: uniedit.git.v1.GitService.CreateRepo:input_type -> uniedit.git.v1.CreateRepoRequest
	4,  // 12: uniedit.git.v1.GitService.ListRepos:input_type -> uniedit.git.v1.ListReposRequest
	0,  // 13: uniedit.git.v1.GitService.GetRepo:input_type -> uniedit.git.v1.GetByIDRequest
	3,  // 14: uniedit.git.v1.GitService.UpdateRepo:input_type -> uniedit.git.v1.UpdateRepoRequest
	0,  // 15: uniedit.git.v1.GitService.DeleteRepo:input_type -> uniedit.git.v1.GetByIDRequest
	0,  // 16: uniedit.git.v1.GitService.GetStorageStats:input_type -> uniedit.git.v1.GetByIDRequest
	8,  // 17: uniedit.git.v1.GitService.AddCollaborator:input_type -> uniedit.git.v1.AddCollaboratorRequest
	0,  // 18: uniedit.git.v1.GitService.ListCollaborators:input_type -> uniedit.git.v1.GetByIDRequest
	10, // 19: uniedit.git.v1.GitService.UpdateCollaborator:input_type -> uniedit.git.v1.UpdateCollaboratorRequest
	11, // 20: uniedit.git.v1.GitService.RemoveCollaborator:input_type -> uniedit.git.v1.RemoveCollaboratorRequest
	13, // 21: uniedit.git.v1.GitService.CreatePR:input_type -> uniedit.git.v1.CreatePRRequest
	14, // 22: uniedit.git.v1.GitService.ListPRs:input_type -> uniedit.git.v1.ListPRsRequest
	16, // 23: uniedit.git.v1.GitService.GetPR:input_type -> uniedit.git.v1.GetPRRequest
	17, // 24: uniedit.git.v1.GitService.UpdatePR:input_type -> uniedit.git.v1.UpdatePRRequest
	16, // 25: uniedit.git.v1.GitService.MergePR:input_type -> uniedit.git.v1.GetPRRequest
	4,  // 26: uniedit.git.v1.GitPublicService.ListPublicRepos:input_type -> uniedit.git.v1.ListReposRequest
	1,  // 27: uniedit.git.v1.GitService.CreateRepo:output_type -> uniedit.git.v1.Repo
	5,  // 28: uniedit.git.v1.GitService.ListRepos:output_type -> uniedit.git.v1.ListReposResponse
	1,  // 29: uniedit.git.v1.GitService.GetRepo:output_type -> uniedit.git.v1.Repo
	1,  // 30: uniedit.git.v1.GitService.UpdateRepo:output_type -> uniedit.git.v1.Repo
	20, // 31: uniedit.git.v1.GitService.DeleteRepo:output_type -> uniedit.common.v1.Empty
	6,  // 32: uniedit.git.v1.GitService.GetStorageStats:output_type -> uniedit.git.v1.StorageStats
	20, // 33: uniedit.git.v1.GitService.AddCollaborator:output_type -> uniedit.common.v1.Empty
	9,  // 34: uniedit.git.v1.GitService.ListCollaborators:output_type -> uniedit.git.v1.ListCollaboratorsResponse
	20, // 35: uniedit.git.v1.GitService.UpdateCollaborator:output_type -> uniedit.common.v1.Empty
	20, // 36: uniedit.git.v1.GitService.RemoveCollaborator:output_type -> uniedit.common.v1.Empty
	12, // 37: uniedit.git.v1.GitService.CreatePR:output_type -> uniedit.git.v1.PullRequest
	15, // 38: uniedit.git.v1.GitService.ListPRs:output_type -> uniedit.git.v1.ListPRsResponse
	12, // 39: uniedit.git.v1.GitService.GetPR:output_type -> uniedit.git.v1.PullRequest
	12, // 40: uniedit.git.v1.GitService.UpdatePR:output_type -> uniedit.git.v1.PullRequest
	12, // 41: uniedit.git.v1.GitService.MergePR:output_type -> uniedit.git.v1.PullRequest
	5,  // 42: uniedit.git.v1.GitPublicService.ListPublicRepos:output_type -> uniedit.git.v1.ListReposResponse
	27, // [27:43] is the sub-list for method output_type
	11, // [11:27] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_git_git_proto_init() }
func file_git_git_proto_init() {
	if File_git_git_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_git_git_proto_rawDesc), len(file_git_git_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_git_git_proto_goTypes,
		DependencyIndexes: file_git_git_proto_depIdxs,
		MessageInfos:      file_git_git_proto_msgTypes,
	}.Build()
	File_git_git_proto = out.File
	file_git_git_proto_goTypes = nil
	file_git_git_proto_depIdxs = nil
}
