// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// source: git/git.proto

package gitv1

import (
	gin "github.com/gin-gonic/gin"
	common "github.com/uniedit/server/api/pb/common"
	protohttp "github.com/uniedit/server/internal/transport/protohttp"
)

type GitServiceGinServer interface {
	CreateRepo(c *gin.Context, in *CreateRepoRequest) (*Repo, error)
	ListRepos(c *gin.Context, in *ListReposRequest) (*ListReposResponse, error)
	GetRepo(c *gin.Context, in *GetByIDRequest) (*Repo, error)
	UpdateRepo(c *gin.Context, in *UpdateRepoRequest) (*Repo, error)
	DeleteRepo(c *gin.Context, in *GetByIDRequest) (*common.Empty, error)
	GetStorageStats(c *gin.Context, in *GetByIDRequest) (*StorageStats, error)
	AddCollaborator(c *gin.Context, in *AddCollaboratorRequest) (*common.Empty, error)
	ListCollaborators(c *gin.Context, in *GetByIDRequest) (*ListCollaboratorsResponse, error)
	UpdateCollaborator(c *gin.Context, in *UpdateCollaboratorRequest) (*common.Empty, error)
	RemoveCollaborator(c *gin.Context, in *RemoveCollaboratorRequest) (*common.Empty, error)
	CreatePR(c *gin.Context, in *CreatePRRequest) (*PullRequest, error)
	ListPRs(c *gin.Context, in *ListPRsRequest) (*ListPRsResponse, error)
	GetPR(c *gin.Context, in *GetPRRequest) (*PullRequest, error)
	UpdatePR(c *gin.Context, in *UpdatePRRequest) (*PullRequest, error)
	MergePR(c *gin.Context, in *GetPRRequest) (*PullRequest, error)
}

func RegisterGitServiceGinServer(r gin.IRoutes, srv GitServiceGinServer) {
	r.Handle("POST", "/repos", _GitService_CreateRepo0_Gin_Handler(srv))
	r.Handle("GET", "/repos", _GitService_ListRepos0_Gin_Handler(srv))
	r.Handle("GET", "/repos/:id", _GitService_GetRepo0_Gin_Handler(srv))
	r.Handle("PUT", "/repos/:id", _GitService_UpdateRepo0_Gin_Handler(srv))
	r.Handle("DELETE", "/repos/:id", _GitService_DeleteRepo0_Gin_Handler(srv))
	r.Handle("GET", "/repos/:id/storage", _GitService_GetStorageStats0_Gin_Handler(srv))
	r.Handle("POST", "/repos/:id/collaborators", _GitService_AddCollaborator0_Gin_Handler(srv))
	r.Handle("GET", "/repos/:id/collaborators", _GitService_ListCollaborators0_Gin_Handler(srv))
	r.Handle("PUT", "/repos/:id/collaborators/:user_id", _GitService_UpdateCollaborator0_Gin_Handler(srv))
	r.Handle("DELETE", "/repos/:id/collaborators/:user_id", _GitService_RemoveCollaborator0_Gin_Handler(srv))
	r.Handle("POST", "/repos/:id/pulls", _GitService_CreatePR0_Gin_Handler(srv))
	r.Handle("GET", "/repos/:id/pulls", _GitService_ListPRs0_Gin_Handler(srv))
	r.Handle("GET", "/repos/:id/pulls/:number", _GitService_GetPR0_Gin_Handler(srv))
	r.Handle("PUT", "/repos/:id/pulls/:number", _GitService_UpdatePR0_Gin_Handler(srv))
	r.Handle("POST", "/repos/:id/pulls/:number/merge", _GitService_MergePR0_Gin_Handler(srv))
}

func _GitService_CreateRepo0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CreateRepoRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.CreateRepo(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_ListRepos0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ListReposRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListRepos(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_GetRepo0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetRepo(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_UpdateRepo0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in UpdateRepoRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.UpdateRepo(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_DeleteRepo0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.DeleteRepo(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_GetStorageStats0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetStorageStats(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_AddCollaborator0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in AddCollaboratorRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.AddCollaborator(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_ListCollaborators0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListCollaborators(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_UpdateCollaborator0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in UpdateCollaboratorRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id", "user_id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.UpdateCollaborator(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_RemoveCollaborator0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in RemoveCollaboratorRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id", "user_id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.RemoveCollaborator(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_CreatePR0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CreatePRRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.CreatePR(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_ListPRs0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ListPRsRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListPRs(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_GetPR0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetPRRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id", "number"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetPR(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_UpdatePR0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in UpdatePRRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id", "number"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.UpdatePR(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _GitService_MergePR0_Gin_Handler(srv GitServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetPRRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id", "number"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.MergePR(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

type GitPublicServiceGinServer interface {
	ListPublicRepos(c *gin.Context, in *ListReposRequest) (*ListReposResponse, error)
}

func RegisterGitPublicServiceGinServer(r gin.IRoutes, srv GitPublicServiceGinServer) {
	r.Handle("GET", "/repos/public", _GitPublicService_ListPublicRepos0_Gin_Handler(srv))
}

func _GitPublicService_ListPublicRepos0_Gin_Handler(srv GitPublicServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ListReposRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListPublicRepos(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}
