// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: billing/billing.proto

package billingv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	common "github.com/uniedit/server/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_billing_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Plan struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                   string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                   string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description            string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	BillingCycle           string                 `protobuf:"bytes,5,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	PriceUsd               int64                  `protobuf:"varint,6,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	MonthlyTokens          int64                  `protobuf:"varint,7,opt,name=monthly_tokens,json=monthlyTokens,proto3" json:"monthly_tokens,omitempty"`
	DailyRequests          int32                  `protobuf:"varint,8,opt,name=daily_requests,json=dailyRequests,proto3" json:"daily_requests,omitempty"`
	MaxApiKeys             int32                  `protobuf:"varint,9,opt,name=max_api_keys,json=maxApiKeys,proto3" json:"max_api_keys,omitempty"`
	Features               []string               `protobuf:"bytes,10,rep,name=features,proto3" json:"features,omitempty"`
	MonthlyChatTokens      int64                  `protobuf:"varint,11,opt,name=monthly_chat_tokens,json=monthlyChatTokens,proto3" json:"monthly_chat_tokens,omitempty"`
	MonthlyImageCredits    int32                  `protobuf:"varint,12,opt,name=monthly_image_credits,json=monthlyImageCredits,proto3" json:"monthly_image_credits,omitempty"`
	MonthlyVideoMinutes    int32                  `protobuf:"varint,13,opt,name=monthly_video_minutes,json=monthlyVideoMinutes,proto3" json:"monthly_video_minutes,omitempty"`
	MonthlyEmbeddingTokens int64                  `protobuf:"varint,14,opt,name=monthly_embedding_tokens,json=monthlyEmbeddingTokens,proto3" json:"monthly_embedding_tokens,omitempty"`
	GitStorageMb           int64                  `protobuf:"varint,15,opt,name=git_storage_mb,json=gitStorageMb,proto3" json:"git_storage_mb,omitempty"`
	LfsStorageMb           int64                  `protobuf:"varint,16,opt,name=lfs_storage_mb,json=lfsStorageMb,proto3" json:"lfs_storage_mb,omitempty"`
	MaxTeamMembers         int32                  `protobuf:"varint,17,opt,name=max_team_members,json=maxTeamMembers,proto3" json:"max_team_members,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_billing_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{1}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plan) GetBillingCycle() string {
	if x != nil {
		return x.BillingCycle
	}
	return ""
}

func (x *Plan) GetPriceUsd() int64 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

func (x *Plan) GetMonthlyTokens() int64 {
	if x != nil {
		return x.MonthlyTokens
	}
	return 0
}

func (x *Plan) GetDailyRequests() int32 {
	if x != nil {
		return x.DailyRequests
	}
	return 0
}

func (x *Plan) GetMaxApiKeys() int32 {
	if x != nil {
		return x.MaxApiKeys
	}
	return 0
}

func (x *Plan) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Plan) GetMonthlyChatTokens() int64 {
	if x != nil {
		return x.MonthlyChatTokens
	}
	return 0
}

func (x *Plan) GetMonthlyImageCredits() int32 {
	if x != nil {
		return x.MonthlyImageCredits
	}
	return 0
}

func (x *Plan) GetMonthlyVideoMinutes() int32 {
	if x != nil {
		return x.MonthlyVideoMinutes
	}
	return 0
}

func (x *Plan) GetMonthlyEmbeddingTokens() int64 {
	if x != nil {
		return x.MonthlyEmbeddingTokens
	}
	return 0
}

func (x *Plan) GetGitStorageMb() int64 {
	if x != nil {
		return x.GitStorageMb
	}
	return 0
}

func (x *Plan) GetLfsStorageMb() int64 {
	if x != nil {
		return x.LfsStorageMb
	}
	return 0
}

func (x *Plan) GetMaxTeamMembers() int32 {
	if x != nil {
		return x.MaxTeamMembers
	}
	return 0
}

type ListPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*Plan                `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansResponse) Reset() {
	*x = ListPlansResponse{}
	mi := &file_billing_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansResponse) ProtoMessage() {}

func (x *ListPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansResponse.ProtoReflect.Descriptor instead.
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{2}
}

func (x *ListPlansResponse) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type Subscription struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanId             string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentPeriodStart string                 `protobuf:"bytes,4,opt,name=current_period_start,json=currentPeriodStart,proto3" json:"current_period_start,omitempty"`
	CurrentPeriodEnd   string                 `protobuf:"bytes,5,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	CancelAtPeriodEnd  bool                   `protobuf:"varint,6,opt,name=cancel_at_period_end,json=cancelAtPeriodEnd,proto3" json:"cancel_at_period_end,omitempty"`
	CanceledAt         string                 `protobuf:"bytes,7,opt,name=canceled_at,json=canceledAt,proto3" json:"canceled_at,omitempty"`
	CreditsBalance     int64                  `protobuf:"varint,8,opt,name=credits_balance,json=creditsBalance,proto3" json:"credits_balance,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Plan               *Plan                  `protobuf:"bytes,10,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_billing_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{3}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetCurrentPeriodStart() string {
	if x != nil {
		return x.CurrentPeriodStart
	}
	return ""
}

func (x *Subscription) GetCurrentPeriodEnd() string {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return ""
}

func (x *Subscription) GetCancelAtPeriodEnd() bool {
	if x != nil {
		return x.CancelAtPeriodEnd
	}
	return false
}

func (x *Subscription) GetCanceledAt() string {
	if x != nil {
		return x.CanceledAt
	}
	return ""
}

func (x *Subscription) GetCreditsBalance() int64 {
	if x != nil {
		return x.CreditsBalance
	}
	return 0
}

func (x *Subscription) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Subscription) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_billing_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSubscriptionRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type CancelSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Immediately   bool                   `protobuf:"varint,1,opt,name=immediately,proto3" json:"immediately,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_billing_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{5}
}

func (x *CancelSubscriptionRequest) GetImmediately() bool {
	if x != nil {
		return x.Immediately
	}
	return false
}

type QuotaStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Plan            string                 `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	TokensUsed      int64                  `protobuf:"varint,2,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	TokensLimit     int64                  `protobuf:"varint,3,opt,name=tokens_limit,json=tokensLimit,proto3" json:"tokens_limit,omitempty"`
	TokensRemaining int64                  `protobuf:"varint,4,opt,name=tokens_remaining,json=tokensRemaining,proto3" json:"tokens_remaining,omitempty"`
	RequestsToday   int32                  `protobuf:"varint,5,opt,name=requests_today,json=requestsToday,proto3" json:"requests_today,omitempty"`
	RequestsLimit   int32                  `protobuf:"varint,6,opt,name=requests_limit,json=requestsLimit,proto3" json:"requests_limit,omitempty"`
	ResetAt         string                 `protobuf:"bytes,7,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuotaStatus) Reset() {
	*x = QuotaStatus{}
	mi := &file_billing_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaStatus) ProtoMessage() {}

func (x *QuotaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaStatus.ProtoReflect.Descriptor instead.
func (*QuotaStatus) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{6}
}

func (x *QuotaStatus) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *QuotaStatus) GetTokensUsed() int64 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *QuotaStatus) GetTokensLimit() int64 {
	if x != nil {
		return x.TokensLimit
	}
	return 0
}

func (x *QuotaStatus) GetTokensRemaining() int64 {
	if x != nil {
		return x.TokensRemaining
	}
	return 0
}

func (x *QuotaStatus) GetRequestsToday() int32 {
	if x != nil {
		return x.RequestsToday
	}
	return 0
}

func (x *QuotaStatus) GetRequestsLimit() int32 {
	if x != nil {
		return x.RequestsLimit
	}
	return 0
}

func (x *QuotaStatus) GetResetAt() string {
	if x != nil {
		return x.ResetAt
	}
	return ""
}

type CheckQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      string                 `protobuf:"bytes,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQuotaRequest) Reset() {
	*x = CheckQuotaRequest{}
	mi := &file_billing_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQuotaRequest) ProtoMessage() {}

func (x *CheckQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQuotaRequest.ProtoReflect.Descriptor instead.
func (*CheckQuotaRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{7}
}

func (x *CheckQuotaRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type CheckQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckQuotaResponse) Reset() {
	*x = CheckQuotaResponse{}
	mi := &file_billing_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckQuotaResponse) ProtoMessage() {}

func (x *CheckQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckQuotaResponse.ProtoReflect.Descriptor instead.
func (*CheckQuotaResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{8}
}

func (x *CheckQuotaResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_billing_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{9}
}

func (x *GetBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GetUsageStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Start         string                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageStatsRequest) Reset() {
	*x = GetUsageStatsRequest{}
	mi := &file_billing_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageStatsRequest) ProtoMessage() {}

func (x *GetUsageStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUsageStatsRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{10}
}

func (x *GetUsageStatsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetUsageStatsRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetUsageStatsRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type UsageStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalTokens   int64                  `protobuf:"varint,1,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalRequests int32                  `protobuf:"varint,2,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalCostUsd  float64                `protobuf:"fixed64,3,opt,name=total_cost_usd,json=totalCostUsd,proto3" json:"total_cost_usd,omitempty"`
	ByModel       map[string]*ModelUsage `protobuf:"bytes,4,rep,name=by_model,json=byModel,proto3" json:"by_model,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ByDay         []*DailyUsage          `protobuf:"bytes,5,rep,name=by_day,json=byDay,proto3" json:"by_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageStats) Reset() {
	*x = UsageStats{}
	mi := &file_billing_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStats) ProtoMessage() {}

func (x *UsageStats) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStats.ProtoReflect.Descriptor instead.
func (*UsageStats) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{11}
}

func (x *UsageStats) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *UsageStats) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *UsageStats) GetTotalCostUsd() float64 {
	if x != nil {
		return x.TotalCostUsd
	}
	return 0
}

func (x *UsageStats) GetByModel() map[string]*ModelUsage {
	if x != nil {
		return x.ByModel
	}
	return nil
}

func (x *UsageStats) GetByDay() []*DailyUsage {
	if x != nil {
		return x.ByDay
	}
	return nil
}

type ModelUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	TotalTokens   int64                  `protobuf:"varint,2,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalRequests int32                  `protobuf:"varint,3,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalCostUsd  float64                `protobuf:"fixed64,4,opt,name=total_cost_usd,json=totalCostUsd,proto3" json:"total_cost_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelUsage) Reset() {
	*x = ModelUsage{}
	mi := &file_billing_billing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUsage) ProtoMessage() {}

func (x *ModelUsage) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUsage.ProtoReflect.Descriptor instead.
func (*ModelUsage) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{12}
}

func (x *ModelUsage) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelUsage) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ModelUsage) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *ModelUsage) GetTotalCostUsd() float64 {
	if x != nil {
		return x.TotalCostUsd
	}
	return 0
}

type DailyUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TotalTokens   int64                  `protobuf:"varint,2,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalRequests int32                  `protobuf:"varint,3,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalCostUsd  float64                `protobuf:"fixed64,4,opt,name=total_cost_usd,json=totalCostUsd,proto3" json:"total_cost_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyUsage) Reset() {
	*x = DailyUsage{}
	mi := &file_billing_billing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyUsage) ProtoMessage() {}

func (x *DailyUsage) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyUsage.ProtoReflect.Descriptor instead.
func (*DailyUsage) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{13}
}

func (x *DailyUsage) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyUsage) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *DailyUsage) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *DailyUsage) GetTotalCostUsd() float64 {
	if x != nil {
		return x.TotalCostUsd
	}
	return 0
}

type RecordUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	ProviderId    string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	InputTokens   int32                  `protobuf:"varint,5,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,6,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CostUsd       float64                `protobuf:"fixed64,7,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,8,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Success       bool                   `protobuf:"varint,9,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordUsageRequest) Reset() {
	*x = RecordUsageRequest{}
	mi := &file_billing_billing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUsageRequest) ProtoMessage() {}

func (x *RecordUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUsageRequest.ProtoReflect.Descriptor instead.
func (*RecordUsageRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{14}
}

func (x *RecordUsageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RecordUsageRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *RecordUsageRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *RecordUsageRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *RecordUsageRequest) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *RecordUsageRequest) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *RecordUsageRequest) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *RecordUsageRequest) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RecordUsageRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddCreditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCreditsRequest) Reset() {
	*x = AddCreditsRequest{}
	mi := &file_billing_billing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCreditsRequest) ProtoMessage() {}

func (x *AddCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCreditsRequest.ProtoReflect.Descriptor instead.
func (*AddCreditsRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{15}
}

func (x *AddCreditsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCreditsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AddCreditsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_billing_billing_proto protoreflect.FileDescriptor

const file_billing_billing_proto_rawDesc = "" +
	"\n" +
	"\x15billing/billing.proto\x12\x12uniedit.billing.v1\x1a\x13common/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf6\x04\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rbilling_cycle\x18\x05 \x01(\tR\fbillingCycle\x12\x1b\n" +
	"\tprice_usd\x18\x06 \x01(\x03R\bpriceUsd\x12%\n" +
	"\x0emonthly_tokens\x18\a \x01(\x03R\rmonthlyTokens\x12%\n" +
	"\x0edaily_requests\x18\b \x01(\x05R\rdailyRequests\x12 \n" +
	"\fmax_api_keys\x18\t \x01(\x05R\n" +
	"maxApiKeys\x12\x1a\n" +
	"\bfeatures\x18\n" +
	" \x03(\tR\bfeatures\x12.\n" +
	"\x13monthly_chat_tokens\x18\v \x01(\x03R\x11monthlyChatTokens\x122\n" +
	"\x15monthly_image_credits\x18\f \x01(\x05R\x13monthlyImageCredits\x122\n" +
	"\x15monthly_video_minutes\x18\r \x01(\x05R\x13monthlyVideoMinutes\x128\n" +
	"\x18monthly_embedding_tokens\x18\x0e \x01(\x03R\x16monthlyEmbeddingTokens\x12$\n" +
	"\x0egit_storage_mb\x18\x0f \x01(\x03R\fgitStorageMb\x12$\n" +
	"\x0elfs_storage_mb\x18\x10 \x01(\x03R\flfsStorageMb\x12(\n" +
	"\x10max_team_members\x18\x11 \x01(\x05R\x0emaxTeamMembers\"C\n" +
	"\x11ListPlansResponse\x12.\n" +
	"\x05plans\x18\x01 \x03(\v2\x18.uniedit.billing.v1.PlanR\x05plans\"\xf7\x02\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x120\n" +
	"\x14current_period_start\x18\x04 \x01(\tR\x12currentPeriodStart\x12,\n" +
	"\x12current_period_end\x18\x05 \x01(\tR\x10currentPeriodEnd\x12/\n" +
	"\x14cancel_at_period_end\x18\x06 \x01(\bR\x11cancelAtPeriodEnd\x12\x1f\n" +
	"\vcanceled_at\x18\a \x01(\tR\n" +
	"canceledAt\x12'\n" +
	"\x0fcredits_balance\x18\b \x01(\x03R\x0ecreditsBalance\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12,\n" +
	"\x04plan\x18\n" +
	" \x01(\v2\x18.uniedit.billing.v1.PlanR\x04plan\"4\n" +
	"\x19CreateSubscriptionRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\"=\n" +
	"\x19CancelSubscriptionRequest\x12 \n" +
	"\vimmediately\x18\x01 \x01(\bR\vimmediately\"\xf9\x01\n" +
	"\vQuotaStatus\x12\x12\n" +
	"\x04plan\x18\x01 \x01(\tR\x04plan\x12\x1f\n" +
	"\vtokens_used\x18\x02 \x01(\x03R\n" +
	"tokensUsed\x12!\n" +
	"\ftokens_limit\x18\x03 \x01(\x03R\vtokensLimit\x12)\n" +
	"\x10tokens_remaining\x18\x04 \x01(\x03R\x0ftokensRemaining\x12%\n" +
	"\x0erequests_today\x18\x05 \x01(\x05R\rrequestsToday\x12%\n" +
	"\x0erequests_limit\x18\x06 \x01(\x05R\rrequestsLimit\x12\x19\n" +
	"\breset_at\x18\a \x01(\tR\aresetAt\"0\n" +
	"\x11CheckQuotaRequest\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\tR\btaskType\".\n" +
	"\x12CheckQuotaResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\".\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance\"V\n" +
	"\x14GetUsageStatsRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12\x14\n" +
	"\x05start\x18\x02 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\tR\x03end\"\xd7\x02\n" +
	"\n" +
	"UsageStats\x12!\n" +
	"\ftotal_tokens\x18\x01 \x01(\x03R\vtotalTokens\x12%\n" +
	"\x0etotal_requests\x18\x02 \x01(\x05R\rtotalRequests\x12$\n" +
	"\x0etotal_cost_usd\x18\x03 \x01(\x01R\ftotalCostUsd\x12F\n" +
	"\bby_model\x18\x04 \x03(\v2+.uniedit.billing.v1.UsageStats.ByModelEntryR\abyModel\x125\n" +
	"\x06by_day\x18\x05 \x03(\v2\x1e.uniedit.billing.v1.DailyUsageR\x05byDay\x1aZ\n" +
	"\fByModelEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.uniedit.billing.v1.ModelUsageR\x05value:\x028\x01\"\x97\x01\n" +
	"\n" +
	"ModelUsage\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12!\n" +
	"\ftotal_tokens\x18\x02 \x01(\x03R\vtotalTokens\x12%\n" +
	"\x0etotal_requests\x18\x03 \x01(\x05R\rtotalRequests\x12$\n" +
	"\x0etotal_cost_usd\x18\x04 \x01(\x01R\ftotalCostUsd\"\x90\x01\n" +
	"\n" +
	"DailyUsage\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12!\n" +
	"\ftotal_tokens\x18\x02 \x01(\x03R\vtotalTokens\x12%\n" +
	"\x0etotal_requests\x18\x03 \x01(\x05R\rtotalRequests\x12$\n" +
	"\x0etotal_cost_usd\x18\x04 \x01(\x01R\ftotalCostUsd\"\xa8\x02\n" +
	"\x12RecordUsageRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\tR\amodelId\x12!\n" +
	"\finput_tokens\x18\x05 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x06 \x01(\x05R\foutputTokens\x12\x19\n" +
	"\bcost_usd\x18\a \x01(\x01R\acostUsd\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\b \x01(\x05R\tlatencyMs\x12\x18\n" +
	"\asuccess\x18\t \x01(\bR\asuccess\"\\\n" +
	"\x11AddCreditsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source2\xe2\x01\n" +
	"\x14BillingPublicService\x12d\n" +
	"\tListPlans\x12\x18.uniedit.common.v1.Empty\x1a%.uniedit.billing.v1.ListPlansResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/billing/plans\x12d\n" +
	"\aGetPlan\x12\".uniedit.billing.v1.GetByIDRequest\x1a\x18.uniedit.billing.v1.Plan\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/billing/plans/{id}2\xcf\a\n" +
	"\x0eBillingService\x12l\n" +
	"\x0fGetSubscription\x12\x18.uniedit.common.v1.Empty\x1a .uniedit.billing.v1.Subscription\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/billing/subscription\x12\x87\x01\n" +
	"\x12CreateSubscription\x12-.uniedit.billing.v1.CreateSubscriptionRequest\x1a .uniedit.billing.v1.Subscription\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/billing/subscription\x12\x8e\x01\n" +
	"\x12CancelSubscription\x12-.uniedit.billing.v1.CancelSubscriptionRequest\x1a .uniedit.billing.v1.Subscription\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/billing/subscription/cancel\x12c\n" +
	"\x0eGetQuotaStatus\x12\x18.uniedit.common.v1.Empty\x1a\x1f.uniedit.billing.v1.QuotaStatus\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/billing/quota\x12|\n" +
	"\n" +
	"CheckQuota\x12%.uniedit.billing.v1.CheckQuotaRequest\x1a&.uniedit.billing.v1.CheckQuotaResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/billing/quota/check\x12h\n" +
	"\n" +
	"GetBalance\x12\x18.uniedit.common.v1.Empty\x1a&.uniedit.billing.v1.GetBalanceResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/billing/credits\x12q\n" +
	"\rGetUsageStats\x12(.uniedit.billing.v1.GetUsageStatsRequest\x1a\x1e.uniedit.billing.v1.UsageStats\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/billing/usage\x12t\n" +
	"\vRecordUsage\x12&.uniedit.billing.v1.RecordUsageRequest\x1a\".uniedit.common.v1.MessageResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/billing/usage2\x8b\x01\n" +
	"\x13BillingAdminService\x12t\n" +
	"\n" +
	"AddCredits\x12%.uniedit.billing.v1.AddCreditsRequest\x1a\".uniedit.common.v1.MessageResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/billing/creditsB\x9e\x01\x92Ag\x12I\n" +
	"\vUniEdit API\x126UniEdit 后端 API（由 proto 自动生成 OpenAPI）2\x02v1\x1a\x0elocalhost:8080\"\a/api/v1*\x01\x01Z2github.com/uniedit/server/api/pb/billing;billingv1b\x06proto3"

var (
	file_billing_billing_proto_rawDescOnce sync.Once
	file_billing_billing_proto_rawDescData []byte
)

func file_billing_billing_proto_rawDescGZIP() []byte {
	file_billing_billing_proto_rawDescOnce.Do(func() {
		file_billing_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)))
	})
	return file_billing_billing_proto_rawDescData
}

var file_billing_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_billing_billing_proto_goTypes = []any{
	(*GetByIDRequest)(nil),            // 0: uniedit.billing.v1.GetByIDRequest
	(*Plan)(nil),                      // 1: uniedit.billing.v1.Plan
	(*ListPlansResponse)(nil),         // 2: uniedit.billing.v1.ListPlansResponse
	(*Subscription)(nil),              // 3: uniedit.billing.v1.Subscription
	(*CreateSubscriptionRequest)(nil), // 4: uniedit.billing.v1.CreateSubscriptionRequest
	(*CancelSubscriptionRequest)(nil), // 5: uniedit.billing.v1.CancelSubscriptionRequest
	(*QuotaStatus)(nil),               // 6: uniedit.billing.v1.QuotaStatus
	(*CheckQuotaRequest)(nil),         // 7: uniedit.billing.v1.CheckQuotaRequest
	(*CheckQuotaResponse)(nil),        // 8: uniedit.billing.v1.CheckQuotaResponse
	(*GetBalanceResponse)(nil),        // 9: uniedit.billing.v1.GetBalanceResponse
	(*GetUsageStatsRequest)(nil),      // 10: uniedit.billing.v1.GetUsageStatsRequest
	(*UsageStats)(nil),                // 11: uniedit.billing.v1.UsageStats
	(*ModelUsage)(nil),                // 12: uniedit.billing.v1.ModelUsage
	(*DailyUsage)(nil),                // 13: uniedit.billing.v1.DailyUsage
	(*RecordUsageRequest)(nil),        // 14: uniedit.billing.v1.RecordUsageRequest
	(*AddCreditsRequest)(nil),         // 15: uniedit.billing.v1.AddCreditsRequest
	nil,                               // 16: uniedit.billing.v1.UsageStats.ByModelEntry
	(*common.Empty)(nil),              // 17: uniedit.common.v1.Empty
	(*common.MessageResponse)(nil),    // 18: uniedit.common.v1.MessageResponse
}
var file_billing_billing_proto_depIdxs = []int32{
	1,  // 0: uniedit.billing.v1.ListPlansResponse.plans:type_name -> uniedit.billing.v1.Plan
	1,  // 1: uniedit.billing.v1.Subscription.plan:type_name -> uniedit.billing.v1.Plan
	16, // 2: uniedit.billing.v1.UsageStats.by_model:type_name -> uniedit.billing.v1.UsageStats.ByModelEntry
	13, // 3: uniedit.billing.v1.UsageStats.by_day:type_name -> uniedit.billing.v1.DailyUsage
	12, // 4: uniedit.billing.v1.UsageStats.ByModelEntry.value:type_name -> uniedit.billing.v1.ModelUsage
	17, // 5: uniedit.billing.v1.BillingPublicService.ListPlans:input_type -> uniedit.common.v1.Empty
	0,  // 6: uniedit.billing.v1.BillingPublicService.GetPlan:input_type -> uniedit.billing.v1.GetByIDRequest
	17, // 7: uniedit.billing.v1.BillingService.GetSubscription:input_type -> uniedit.common.v1.Empty
	4,  // 8: uniedit.billing.v1.BillingService.CreateSubscription:input_type -> uniedit.billing.v1.CreateSubscriptionRequest
	5,  // 9: uniedit.billing.v1.BillingService.CancelSubscription:input_type -> uniedit.billing.v1.CancelSubscriptionRequest
	17, // 10: uniedit.billing.v1.BillingService.GetQuotaStatus:input_type -> uniedit.common.v1.Empty
	7,  // 11: uniedit.billing.v1.BillingService.CheckQuota:input_type -> uniedit.billing.v1.CheckQuotaRequest
	17, // 12: uniedit.billing.v1.BillingService.GetBalance:input_type -> uniedit.common.v1.Empty
	10, // 13: uniedit.billing.v1.BillingService.GetUsageStats:input_type -> uniedit.billing.v1.GetUsageStatsRequest
	14, // 14: uniedit.billing.v1.BillingService.RecordUsage:input_type -> uniedit.billing.v1.RecordUsageRequest
	15, // 15: uniedit.billing.v1.BillingAdminService.AddCredits:input_type -> uniedit.billing.v1.AddCreditsRequest
	2,  // 16: uniedit.billing.v1.BillingPublicService.ListPlans:output_type -> uniedit.billing.v1.ListPlansResponse
	1,  // 17: uniedit.billing.v1.BillingPublicService.GetPlan:output_type -> uniedit.billing.v1.Plan
	3,  // 18: uniedit.billing.v1.BillingService.GetSubscription:output_type -> uniedit.billing.v1.Subscription
	3,  // 19: uniedit.billing.v1.BillingService.CreateSubscription:output_type -> uniedit.billing.v1.Subscription
	3,  // 20: uniedit.billing.v1.BillingService.CancelSubscription:output_type -> uniedit.billing.v1.Subscription
	6,  // 21: uniedit.billing.v1.BillingService.GetQuotaStatus:output_type -> uniedit.billing.v1.QuotaStatus
	8,  // 22: uniedit.billing.v1.BillingService.CheckQuota:output_type -> uniedit.billing.v1.CheckQuotaResponse
	9,  // 23: uniedit.billing.v1.BillingService.GetBalance:output_type -> uniedit.billing.v1.GetBalanceResponse
	11, // 24: uniedit.billing.v1.BillingService.GetUsageStats:output_type -> uniedit.billing.v1.UsageStats
	18, // 25: uniedit.billing.v1.BillingService.RecordUsage:output_type -> uniedit.common.v1.MessageResponse
	18, // 26: uniedit.billing.v1.BillingAdminService.AddCredits:output_type -> uniedit.common.v1.MessageResponse
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_billing_billing_proto_init() }
func file_billing_billing_proto_init() {
	if File_billing_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_billing_billing_proto_goTypes,
		DependencyIndexes: file_billing_billing_proto_depIdxs,
		MessageInfos:      file_billing_billing_proto_msgTypes,
	}.Build()
	File_billing_billing_proto = out.File
	file_billing_billing_proto_goTypes = nil
	file_billing_billing_proto_depIdxs = nil
}
