// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// source: auth/auth.proto

package authv1

import (
	gin "github.com/gin-gonic/gin"
	common "github.com/uniedit/server/api/pb/common"
	protohttp "github.com/uniedit/server/internal/transport/protohttp"
)

type AuthOAuthServiceGinServer interface {
	InitiateLogin(c *gin.Context, in *InitiateLoginRequest) (*InitiateLoginResponse, error)
	CompleteLogin(c *gin.Context, in *CompleteLoginRequest) (*CompleteLoginResponse, error)
	RefreshToken(c *gin.Context, in *RefreshTokenRequest) (*TokenPairResponse, error)
	GetMe(c *gin.Context, in *common.Empty) (*GetMeResponse, error)
}

func RegisterAuthOAuthServiceGinServer(r gin.IRoutes, srv AuthOAuthServiceGinServer) {
	r.Handle("POST", "/auth/oauth/:provider", _AuthOAuthService_InitiateLogin0_Gin_Handler(srv))
	r.Handle("POST", "/auth/oauth/:provider/callback", _AuthOAuthService_CompleteLogin0_Gin_Handler(srv))
	r.Handle("POST", "/auth/refresh", _AuthOAuthService_RefreshToken0_Gin_Handler(srv))
	r.Handle("GET", "/auth/me", _AuthOAuthService_GetMe0_Gin_Handler(srv))
}

func _AuthOAuthService_InitiateLogin0_Gin_Handler(srv AuthOAuthServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in InitiateLoginRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "provider"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.InitiateLogin(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthOAuthService_CompleteLogin0_Gin_Handler(srv AuthOAuthServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CompleteLoginRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "provider"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.CompleteLogin(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthOAuthService_RefreshToken0_Gin_Handler(srv AuthOAuthServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in RefreshTokenRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.RefreshToken(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthOAuthService_GetMe0_Gin_Handler(srv AuthOAuthServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in common.Empty
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetMe(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

type AuthSessionServiceGinServer interface {
	Logout(c *gin.Context, in *common.Empty) (*common.MessageResponse, error)
}

func RegisterAuthSessionServiceGinServer(r gin.IRoutes, srv AuthSessionServiceGinServer) {
	r.Handle("POST", "/auth/logout", _AuthSessionService_Logout0_Gin_Handler(srv))
}

func _AuthSessionService_Logout0_Gin_Handler(srv AuthSessionServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in common.Empty
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.Logout(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

type AuthAPIKeyServiceGinServer interface {
	CreateUserAPIKey(c *gin.Context, in *CreateUserAPIKeyRequest) (*UserAPIKey, error)
	ListUserAPIKeys(c *gin.Context, in *common.Empty) (*ListUserAPIKeysResponse, error)
	GetUserAPIKey(c *gin.Context, in *GetByIDRequest) (*UserAPIKey, error)
	DeleteUserAPIKey(c *gin.Context, in *GetByIDRequest) (*common.MessageResponse, error)
	RotateUserAPIKey(c *gin.Context, in *RotateUserAPIKeyRequest) (*UserAPIKey, error)
}

func RegisterAuthAPIKeyServiceGinServer(r gin.IRoutes, srv AuthAPIKeyServiceGinServer) {
	r.Handle("POST", "/api-keys", _AuthAPIKeyService_CreateUserAPIKey0_Gin_Handler(srv))
	r.Handle("GET", "/api-keys", _AuthAPIKeyService_ListUserAPIKeys0_Gin_Handler(srv))
	r.Handle("GET", "/api-keys/:id", _AuthAPIKeyService_GetUserAPIKey0_Gin_Handler(srv))
	r.Handle("DELETE", "/api-keys/:id", _AuthAPIKeyService_DeleteUserAPIKey0_Gin_Handler(srv))
	r.Handle("POST", "/api-keys/:id/rotate", _AuthAPIKeyService_RotateUserAPIKey0_Gin_Handler(srv))
}

func _AuthAPIKeyService_CreateUserAPIKey0_Gin_Handler(srv AuthAPIKeyServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CreateUserAPIKeyRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.CreateUserAPIKey(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthAPIKeyService_ListUserAPIKeys0_Gin_Handler(srv AuthAPIKeyServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in common.Empty
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListUserAPIKeys(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthAPIKeyService_GetUserAPIKey0_Gin_Handler(srv AuthAPIKeyServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetUserAPIKey(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthAPIKeyService_DeleteUserAPIKey0_Gin_Handler(srv AuthAPIKeyServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.DeleteUserAPIKey(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthAPIKeyService_RotateUserAPIKey0_Gin_Handler(srv AuthAPIKeyServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in RotateUserAPIKeyRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.RotateUserAPIKey(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

type AuthSystemAPIKeyServiceGinServer interface {
	CreateSystemAPIKey(c *gin.Context, in *CreateSystemAPIKeyRequest) (*CreateSystemAPIKeyResponse, error)
	ListSystemAPIKeys(c *gin.Context, in *common.Empty) (*ListSystemAPIKeysResponse, error)
	GetSystemAPIKey(c *gin.Context, in *GetByIDRequest) (*SystemAPIKey, error)
	UpdateSystemAPIKey(c *gin.Context, in *UpdateSystemAPIKeyRequest) (*SystemAPIKey, error)
	DeleteSystemAPIKey(c *gin.Context, in *GetByIDRequest) (*common.MessageResponse, error)
	RotateSystemAPIKey(c *gin.Context, in *GetByIDRequest) (*CreateSystemAPIKeyResponse, error)
}

func RegisterAuthSystemAPIKeyServiceGinServer(r gin.IRoutes, srv AuthSystemAPIKeyServiceGinServer) {
	r.Handle("POST", "/system-api-keys", _AuthSystemAPIKeyService_CreateSystemAPIKey0_Gin_Handler(srv))
	r.Handle("GET", "/system-api-keys", _AuthSystemAPIKeyService_ListSystemAPIKeys0_Gin_Handler(srv))
	r.Handle("GET", "/system-api-keys/:id", _AuthSystemAPIKeyService_GetSystemAPIKey0_Gin_Handler(srv))
	r.Handle("PATCH", "/system-api-keys/:id", _AuthSystemAPIKeyService_UpdateSystemAPIKey0_Gin_Handler(srv))
	r.Handle("DELETE", "/system-api-keys/:id", _AuthSystemAPIKeyService_DeleteSystemAPIKey0_Gin_Handler(srv))
	r.Handle("POST", "/system-api-keys/:id/rotate", _AuthSystemAPIKeyService_RotateSystemAPIKey0_Gin_Handler(srv))
}

func _AuthSystemAPIKeyService_CreateSystemAPIKey0_Gin_Handler(srv AuthSystemAPIKeyServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CreateSystemAPIKeyRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.CreateSystemAPIKey(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthSystemAPIKeyService_ListSystemAPIKeys0_Gin_Handler(srv AuthSystemAPIKeyServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in common.Empty
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListSystemAPIKeys(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthSystemAPIKeyService_GetSystemAPIKey0_Gin_Handler(srv AuthSystemAPIKeyServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetSystemAPIKey(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthSystemAPIKeyService_UpdateSystemAPIKey0_Gin_Handler(srv AuthSystemAPIKeyServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in UpdateSystemAPIKeyRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.UpdateSystemAPIKey(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthSystemAPIKeyService_DeleteSystemAPIKey0_Gin_Handler(srv AuthSystemAPIKeyServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.DeleteSystemAPIKey(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AuthSystemAPIKeyService_RotateSystemAPIKey0_Gin_Handler(srv AuthSystemAPIKeyServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.RotateSystemAPIKey(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}
