// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// source: user/user.proto

package userv1

import (
	gin "github.com/gin-gonic/gin"
	common "github.com/uniedit/server/api/pb/common"
	protohttp "github.com/uniedit/server/internal/transport/protohttp"
)

type UserAuthServiceGinServer interface {
	Register(c *gin.Context, in *RegisterRequest) (*RegisterResponse, error)
	VerifyEmail(c *gin.Context, in *VerifyEmailRequest) (*common.MessageResponse, error)
	ResendVerification(c *gin.Context, in *ResendVerificationRequest) (*common.MessageResponse, error)
	RequestPasswordReset(c *gin.Context, in *RequestPasswordResetRequest) (*common.MessageResponse, error)
	CompletePasswordReset(c *gin.Context, in *CompletePasswordResetRequest) (*common.MessageResponse, error)
}

func RegisterUserAuthServiceGinServer(r gin.IRoutes, srv UserAuthServiceGinServer) {
	r.Handle("POST", "/auth/register", _UserAuthService_Register0_Gin_Handler(srv))
	r.Handle("POST", "/auth/verify-email", _UserAuthService_VerifyEmail0_Gin_Handler(srv))
	r.Handle("POST", "/auth/resend-verification", _UserAuthService_ResendVerification0_Gin_Handler(srv))
	r.Handle("POST", "/auth/password-reset", _UserAuthService_RequestPasswordReset0_Gin_Handler(srv))
	r.Handle("POST", "/auth/password-reset/complete", _UserAuthService_CompletePasswordReset0_Gin_Handler(srv))
}

func _UserAuthService_Register0_Gin_Handler(srv UserAuthServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in RegisterRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.Register(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserAuthService_VerifyEmail0_Gin_Handler(srv UserAuthServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in VerifyEmailRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.VerifyEmail(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserAuthService_ResendVerification0_Gin_Handler(srv UserAuthServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ResendVerificationRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ResendVerification(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserAuthService_RequestPasswordReset0_Gin_Handler(srv UserAuthServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in RequestPasswordResetRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.RequestPasswordReset(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserAuthService_CompletePasswordReset0_Gin_Handler(srv UserAuthServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CompletePasswordResetRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.CompletePasswordReset(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

type UserProfileServiceGinServer interface {
	GetMe(c *gin.Context, in *common.Empty) (*common.User, error)
	GetProfile(c *gin.Context, in *common.Empty) (*Profile, error)
	UpdateProfile(c *gin.Context, in *UpdateProfileRequest) (*common.User, error)
	GetPreferences(c *gin.Context, in *common.Empty) (*Preferences, error)
	UpdatePreferences(c *gin.Context, in *UpdatePreferencesRequest) (*common.MessageResponse, error)
	UploadAvatar(c *gin.Context, in *UploadAvatarRequest) (*UploadAvatarResponse, error)
	ChangePassword(c *gin.Context, in *ChangePasswordRequest) (*common.MessageResponse, error)
	DeleteAccount(c *gin.Context, in *DeleteAccountRequest) (*common.MessageResponse, error)
}

func RegisterUserProfileServiceGinServer(r gin.IRoutes, srv UserProfileServiceGinServer) {
	r.Handle("GET", "/users/me", _UserProfileService_GetMe0_Gin_Handler(srv))
	r.Handle("GET", "/users/me/profile", _UserProfileService_GetProfile0_Gin_Handler(srv))
	r.Handle("PUT", "/users/me/profile", _UserProfileService_UpdateProfile0_Gin_Handler(srv))
	r.Handle("GET", "/users/me/preferences", _UserProfileService_GetPreferences0_Gin_Handler(srv))
	r.Handle("PUT", "/users/me/preferences", _UserProfileService_UpdatePreferences0_Gin_Handler(srv))
	r.Handle("POST", "/users/me/avatar", _UserProfileService_UploadAvatar0_Gin_Handler(srv))
	r.Handle("POST", "/users/me/password", _UserProfileService_ChangePassword0_Gin_Handler(srv))
	r.Handle("DELETE", "/users/me", _UserProfileService_DeleteAccount0_Gin_Handler(srv))
}

func _UserProfileService_GetMe0_Gin_Handler(srv UserProfileServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in common.Empty
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetMe(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserProfileService_GetProfile0_Gin_Handler(srv UserProfileServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in common.Empty
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetProfile(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserProfileService_UpdateProfile0_Gin_Handler(srv UserProfileServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in UpdateProfileRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.UpdateProfile(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserProfileService_GetPreferences0_Gin_Handler(srv UserProfileServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in common.Empty
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetPreferences(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserProfileService_UpdatePreferences0_Gin_Handler(srv UserProfileServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in UpdatePreferencesRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.UpdatePreferences(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserProfileService_UploadAvatar0_Gin_Handler(srv UserProfileServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in UploadAvatarRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.UploadAvatar(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserProfileService_ChangePassword0_Gin_Handler(srv UserProfileServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ChangePasswordRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ChangePassword(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserProfileService_DeleteAccount0_Gin_Handler(srv UserProfileServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in DeleteAccountRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.DeleteAccount(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

type UserAdminServiceGinServer interface {
	ListUsers(c *gin.Context, in *ListUsersRequest) (*ListUsersResponse, error)
	GetUser(c *gin.Context, in *GetByIDRequest) (*common.User, error)
	SuspendUser(c *gin.Context, in *SuspendUserRequest) (*common.MessageResponse, error)
	ReactivateUser(c *gin.Context, in *GetByIDRequest) (*common.MessageResponse, error)
	SetAdminStatus(c *gin.Context, in *SetAdminStatusRequest) (*common.MessageResponse, error)
	DeleteUser(c *gin.Context, in *GetByIDRequest) (*common.MessageResponse, error)
}

func RegisterUserAdminServiceGinServer(r gin.IRoutes, srv UserAdminServiceGinServer) {
	r.Handle("GET", "/users", _UserAdminService_ListUsers0_Gin_Handler(srv))
	r.Handle("GET", "/users/:id", _UserAdminService_GetUser0_Gin_Handler(srv))
	r.Handle("POST", "/users/:id/suspend", _UserAdminService_SuspendUser0_Gin_Handler(srv))
	r.Handle("POST", "/users/:id/reactivate", _UserAdminService_ReactivateUser0_Gin_Handler(srv))
	r.Handle("PUT", "/users/:id/admin", _UserAdminService_SetAdminStatus0_Gin_Handler(srv))
	r.Handle("DELETE", "/users/:id", _UserAdminService_DeleteUser0_Gin_Handler(srv))
}

func _UserAdminService_ListUsers0_Gin_Handler(srv UserAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ListUsersRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListUsers(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserAdminService_GetUser0_Gin_Handler(srv UserAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetUser(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserAdminService_SuspendUser0_Gin_Handler(srv UserAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in SuspendUserRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.SuspendUser(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserAdminService_ReactivateUser0_Gin_Handler(srv UserAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ReactivateUser(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserAdminService_SetAdminStatus0_Gin_Handler(srv UserAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in SetAdminStatusRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.SetAdminStatus(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _UserAdminService_DeleteUser0_Gin_Handler(srv UserAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.DeleteUser(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}
