// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"net/http"

	"github.com/redis/go-redis/v9"
	"github.com/uniedit/server/internal/adapter/inbound/http/ai"
	authhttp "github.com/uniedit/server/internal/adapter/inbound/http/auth"
	billinghttp "github.com/uniedit/server/internal/adapter/inbound/http/billing"
	collabhttp "github.com/uniedit/server/internal/adapter/inbound/http/collaboration"
	githttp "github.com/uniedit/server/internal/adapter/inbound/http/git"
	mediahttp "github.com/uniedit/server/internal/adapter/inbound/http/media"
	orderhttp "github.com/uniedit/server/internal/adapter/inbound/http/order"
	paymenthttp "github.com/uniedit/server/internal/adapter/inbound/http/payment"
	userhttp "github.com/uniedit/server/internal/adapter/inbound/http/user"
	"github.com/uniedit/server/internal/adapter/outbound/postgres"
	ai2 "github.com/uniedit/server/internal/domain/ai"
	"github.com/uniedit/server/internal/domain/auth"
	"github.com/uniedit/server/internal/domain/billing"
	"github.com/uniedit/server/internal/domain/order"
	"github.com/uniedit/server/internal/domain/payment"
	"github.com/uniedit/server/internal/domain/user"
	"github.com/uniedit/server/internal/infra/config"
	"github.com/uniedit/server/internal/port/inbound"
	"github.com/uniedit/server/internal/port/outbound"
	"github.com/uniedit/server/internal/utils/logger"
	"github.com/uniedit/server/internal/utils/metrics"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeDependencies creates all dependencies using Wire.
func InitializeDependencies(cfg *config.Config) (*Dependencies, func(), error) {
	db, err := ProvideDatabase(cfg)
	if err != nil {
		return nil, nil, err
	}
	logger, err := ProvideZapLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	universalClient := ProvideRedisClient(cfg, logger)
	client := ProvideHTTPClient(cfg)
	rateLimiterPort := ProvideRateLimiter(universalClient)
	loggerLogger := ProvideLogger(cfg)
	metrics := ProvideMetrics()
	userDatabasePort := postgres.NewUserAdapter(db)
	verificationDatabasePort := postgres.NewVerificationAdapter(db)
	userDomain := ProvideUserDomain(userDatabasePort, verificationDatabasePort, logger)
	refreshTokenDatabasePort := postgres.NewRefreshTokenAdapter(db)
	userAPIKeyDatabasePort := postgres.NewUserAPIKeyAdapter(db)
	systemAPIKeyDatabasePort := postgres.NewSystemAPIKeyAdapter(db)
	oAuthRegistryPort := ProvideOAuthRegistry(cfg)
	oAuthStateStorePort := ProvideOAuthStateStore(universalClient)
	jwtPort := ProvideJWTManager(cfg)
	cryptoPort := ProvideAuthCryptoAdapter(cfg)
	authDomain := ProvideAuthDomain(userDomain, refreshTokenDatabasePort, userAPIKeyDatabasePort, systemAPIKeyDatabasePort, oAuthRegistryPort, oAuthStateStorePort, jwtPort, cryptoPort, logger)
	planDatabasePort := postgres.NewPlanAdapter(db)
	subscriptionDatabasePort := postgres.NewSubscriptionAdapter(db)
	usageRecordDatabasePort := postgres.NewUsageRecordAdapter(db)
	quotaCachePort := ProvideQuotaCache(universalClient)
	billingDomain := ProvideBillingDomain(planDatabasePort, subscriptionDatabasePort, usageRecordDatabasePort, quotaCachePort, logger)
	orderDatabasePort := postgres.NewOrderAdapter(db)
	orderItemDatabasePort := postgres.NewOrderItemAdapter(db)
	invoiceDatabasePort := postgres.NewInvoiceAdapter(db)
	orderDomain := ProvideOrderDomain(orderDatabasePort, orderItemDatabasePort, invoiceDatabasePort, planDatabasePort, logger)
	paymentDatabasePort := postgres.NewPaymentAdapter(db)
	webhookEventDatabasePort := postgres.NewWebhookEventAdapter(db)
	orderReaderPort := ProvideOrderReaderAdapter(orderDomain)
	billingReaderPort := ProvideBillingReaderAdapter(billingDomain)
	eventPublisherPort := ProvideEventPublisher()
	paymentDomain := ProvidePaymentDomain(paymentDatabasePort, webhookEventDatabasePort, orderReaderPort, billingReaderPort, eventPublisherPort, cfg, logger)
	aiProviderDatabasePort := postgres.NewAIProviderAdapter(db)
	aiModelDatabasePort := postgres.NewAIModelAdapter(db)
	aiProviderAccountDatabasePort := postgres.NewAIProviderAccountAdapter(db)
	aiModelGroupDatabasePort := postgres.NewAIModelGroupAdapter(db)
	aiProviderHealthCachePort := ProvideAIHealthCache(universalClient)
	aiEmbeddingCachePort := ProvideAIEmbeddingCache(universalClient)
	aiVendorRegistryPort := ProvideVendorRegistry(client)
	aiCryptoPort := ProvideAICryptoAdapter(cfg)
	aiDomain := ProvideAIDomain(aiProviderDatabasePort, aiModelDatabasePort, aiProviderAccountDatabasePort, aiModelGroupDatabasePort, aiProviderHealthCachePort, aiEmbeddingCachePort, aiVendorRegistryPort, aiCryptoPort, logger)
	gitRepoDatabaseAdapter := postgres.NewGitRepoDatabaseAdapter(db)
	gitCollaboratorDatabaseAdapter := postgres.NewGitCollaboratorDatabaseAdapter(db)
	gitPullRequestDatabaseAdapter := postgres.NewGitPullRequestDatabaseAdapter(db)
	gitLFSObjectDatabaseAdapter := postgres.NewGitLFSObjectDatabaseAdapter(db)
	gitLFSLockDatabaseAdapter := postgres.NewGitLFSLockDatabaseAdapter(db)
	gitDomain := ProvideGitDomain(gitRepoDatabaseAdapter, gitCollaboratorDatabaseAdapter, gitPullRequestDatabaseAdapter, gitLFSObjectDatabaseAdapter, gitLFSLockDatabaseAdapter, cfg, logger)
	teamAdapter := postgres.NewTeamAdapter(db)
	teamMemberAdapter := postgres.NewTeamMemberAdapter(db)
	teamInvitationAdapter := postgres.NewTeamInvitationAdapter(db)
	collaborationUserLookupAdapter := postgres.NewCollaborationUserLookupAdapter(db)
	collaborationTransactionAdapter := postgres.NewCollaborationTransactionAdapter(db)
	collaborationDomain := ProvideCollaborationDomain(teamAdapter, teamMemberAdapter, teamInvitationAdapter, collaborationUserLookupAdapter, collaborationTransactionAdapter, cfg, logger)
	mediaProviderDBAdapter := postgres.NewMediaProviderDBAdapter(db)
	mediaModelDBAdapter := postgres.NewMediaModelDBAdapter(db)
	mediaTaskDBAdapter := postgres.NewMediaTaskDBAdapter(db)
	mediaProviderHealthCachePort := ProvideMediaHealthCache(universalClient)
	mediaVendorRegistryPort := ProvideMediaVendorRegistry(client)
	mediaCryptoPort := ProvideMediaCryptoAdapter(cfg)
	mediaDomain := ProvideMediaDomain(mediaProviderDBAdapter, mediaModelDBAdapter, mediaTaskDBAdapter, mediaProviderHealthCachePort, mediaVendorRegistryPort, mediaCryptoPort, logger)
	chatHandler := ai.NewChatHandler(aiDomain)
	providerAdminHandler := ProvideAIProviderAdminHandler(aiDomain)
	modelAdminHandler := ProvideAIModelAdminHandler(aiDomain)
	publicHandler := ProvideAIPublicHandler(aiDomain)
	oAuthHandler := authhttp.NewOAuthHandler(authDomain)
	apiKeyHandler := authhttp.NewAPIKeyHandler(authDomain)
	systemAPIKeyHandler := authhttp.NewSystemAPIKeyHandler(authDomain)
	profileHandler := userhttp.NewProfileHandler(userDomain)
	registrationHandler := userhttp.NewRegistrationHandler(userDomain)
	adminHandler := userhttp.NewAdminHandler(userDomain)
	subscriptionHandler := billinghttp.NewSubscriptionHandler(billingDomain)
	quotaHandler := billinghttp.NewQuotaHandler(billingDomain)
	creditsHandler := billinghttp.NewCreditsHandler(billingDomain)
	usageHandler := billinghttp.NewUsageHandler(billingDomain)
	orderHandler := orderhttp.NewOrderHandler(orderDomain)
	invoiceHandler := orderhttp.NewInvoiceHandler(orderDomain)
	paymentHandler := paymenthttp.NewPaymentHandler(paymentDomain)
	refundHandler := paymenthttp.NewRefundHandler(paymentDomain)
	webhookHandler := paymenthttp.NewWebhookHandler(paymentDomain)
	handler := ProvideGitHandler(gitDomain, cfg)
	collabhttpHandler := ProvideCollaborationHandler(collaborationDomain, cfg)
	mediahttpHandler := ProvideMediaHandler(mediaDomain)
	dependencies := &Dependencies{
		Config:                 cfg,
		DB:                     db,
		Redis:                  universalClient,
		HTTPClient:             client,
		RateLimiter:            rateLimiterPort,
		Logger:                 loggerLogger,
		ZapLogger:              logger,
		Metrics:                metrics,
		UserDomain:             userDomain,
		AuthDomain:             authDomain,
		BillingDomain:          billingDomain,
		OrderDomain:            orderDomain,
		PaymentDomain:          paymentDomain,
		AIDomain:               aiDomain,
		GitDomain:              gitDomain,
		CollaborationDomain:    collaborationDomain,
		MediaDomain:            mediaDomain,
		AIChatHandler:          chatHandler,
		AIProviderAdminHandler: providerAdminHandler,
		AIModelAdminHandler:    modelAdminHandler,
		AIPublicHandler:        publicHandler,
		OAuthHandler:           oAuthHandler,
		APIKeyHandler:          apiKeyHandler,
		SystemAPIKeyHandler:    systemAPIKeyHandler,
		ProfileHandler:         profileHandler,
		RegistrationHandler:    registrationHandler,
		UserAdminHandler:       adminHandler,
		SubscriptionHandler:    subscriptionHandler,
		QuotaHandler:           quotaHandler,
		CreditsHandler:         creditsHandler,
		UsageHandler:           usageHandler,
		OrderHandler:           orderHandler,
		InvoiceHandler:         invoiceHandler,
		PaymentHandler:         paymentHandler,
		RefundHandler:          refundHandler,
		WebhookHandler:         webhookHandler,
		GitHandler:             handler,
		CollaborationHandler:   collabhttpHandler,
		MediaHandler:           mediahttpHandler,
	}
	return dependencies, func() {
	}, nil
}

// wire.go:

// Dependencies holds all injected dependencies.
type Dependencies struct {
	Config      *config.Config
	DB          *gorm.DB
	Redis       redis.UniversalClient
	HTTPClient  *http.Client
	RateLimiter outbound.RateLimiterPort
	Logger      *logger.Logger
	ZapLogger   *zap.Logger
	Metrics     *metrics.Metrics

	// Domains
	UserDomain          user.UserDomain
	AuthDomain          auth.AuthDomain
	BillingDomain       billing.BillingDomain
	OrderDomain         order.OrderDomain
	PaymentDomain       payment.PaymentDomain
	AIDomain            ai2.AIDomain
	GitDomain           inbound.GitDomain
	CollaborationDomain inbound.CollaborationDomain
	MediaDomain         inbound.MediaDomain

	// AI HTTP Handlers
	AIChatHandler          *ai.ChatHandler
	AIProviderAdminHandler *ai.ProviderAdminHandler
	AIModelAdminHandler    *ai.ModelAdminHandler
	AIPublicHandler        *ai.PublicHandler

	// Auth HTTP Handlers
	OAuthHandler        *authhttp.OAuthHandler
	APIKeyHandler       *authhttp.APIKeyHandler
	SystemAPIKeyHandler *authhttp.SystemAPIKeyHandler

	// User HTTP Handlers
	ProfileHandler      *userhttp.ProfileHandler
	RegistrationHandler *userhttp.RegistrationHandler
	UserAdminHandler    *userhttp.AdminHandler

	// Billing HTTP Handlers
	SubscriptionHandler *billinghttp.SubscriptionHandler
	QuotaHandler        *billinghttp.QuotaHandler
	CreditsHandler      *billinghttp.CreditsHandler
	UsageHandler        *billinghttp.UsageHandler

	// Order HTTP Handlers
	OrderHandler   *orderhttp.OrderHandler
	InvoiceHandler *orderhttp.InvoiceHandler

	// Payment HTTP Handlers
	PaymentHandler *paymenthttp.PaymentHandler
	RefundHandler  *paymenthttp.RefundHandler
	WebhookHandler *paymenthttp.WebhookHandler

	// Git HTTP Handlers
	GitHandler *githttp.Handler

	// Collaboration HTTP Handlers
	CollaborationHandler *collabhttp.Handler

	// Media HTTP Handlers
	MediaHandler *mediahttp.Handler
}
