// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/redis/go-redis/v9"
	"github.com/uniedit/server/internal/adapter/inbound/http/ai"
	"github.com/uniedit/server/internal/adapter/inbound/http/aiproto"
	"github.com/uniedit/server/internal/adapter/inbound/http/authproto"
	"github.com/uniedit/server/internal/adapter/inbound/http/billing"
	"github.com/uniedit/server/internal/adapter/inbound/http/billingproto"
	"github.com/uniedit/server/internal/adapter/inbound/http/collaboration"
	"github.com/uniedit/server/internal/adapter/inbound/http/collaborationproto"
	"github.com/uniedit/server/internal/adapter/inbound/http/git"
	"github.com/uniedit/server/internal/adapter/inbound/http/gitproto"
	"github.com/uniedit/server/internal/adapter/inbound/http/media"
	"github.com/uniedit/server/internal/adapter/inbound/http/mediaproto"
	"github.com/uniedit/server/internal/adapter/inbound/http/orderproto"
	"github.com/uniedit/server/internal/adapter/inbound/http/payment"
	"github.com/uniedit/server/internal/adapter/inbound/http/paymentproto"
	"github.com/uniedit/server/internal/adapter/inbound/http/pingproto"
	"github.com/uniedit/server/internal/adapter/inbound/http/userproto"
	"github.com/uniedit/server/internal/adapter/outbound/postgres"
	ai2 "github.com/uniedit/server/internal/domain/ai"
	"github.com/uniedit/server/internal/domain/auth"
	"github.com/uniedit/server/internal/domain/billing"
	"github.com/uniedit/server/internal/domain/order"
	"github.com/uniedit/server/internal/domain/payment"
	"github.com/uniedit/server/internal/domain/user"
	"github.com/uniedit/server/internal/infra/config"
	"github.com/uniedit/server/internal/port/inbound"
	"github.com/uniedit/server/internal/port/outbound"
	"github.com/uniedit/server/internal/utils/logger"
	"github.com/uniedit/server/internal/utils/metrics"
	"go.uber.org/zap"
	"gorm.io/gorm"
	"net/http"
)

// Injectors from wire.go:

// InitializeDependencies creates all dependencies using Wire.
func InitializeDependencies(cfg *config.Config) (*Dependencies, func(), error) {
	db, err := ProvideDatabase(cfg)
	if err != nil {
		return nil, nil, err
	}
	logger, err := ProvideZapLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	universalClient := ProvideRedisClient(cfg, logger)
	client := ProvideHTTPClient(cfg)
	rateLimiterPort := ProvideRateLimiter(universalClient)
	loggerLogger := ProvideLogger(cfg)
	metrics := ProvideMetrics()
	userDatabasePort := postgres.NewUserAdapter(db)
	verificationDatabasePort := postgres.NewVerificationAdapter(db)
	userDomain := ProvideUserDomain(userDatabasePort, verificationDatabasePort, logger)
	refreshTokenDatabasePort := postgres.NewRefreshTokenAdapter(db)
	userAPIKeyDatabasePort := postgres.NewUserAPIKeyAdapter(db)
	systemAPIKeyDatabasePort := postgres.NewSystemAPIKeyAdapter(db)
	oAuthRegistryPort := ProvideOAuthRegistry(cfg)
	oAuthStateStorePort := ProvideOAuthStateStore(universalClient)
	jwtPort := ProvideJWTManager(cfg)
	cryptoPort := ProvideAuthCryptoAdapter(cfg)
	authDomain := ProvideAuthDomain(userDomain, refreshTokenDatabasePort, userAPIKeyDatabasePort, systemAPIKeyDatabasePort, oAuthRegistryPort, oAuthStateStorePort, jwtPort, cryptoPort, logger)
	planDatabasePort := postgres.NewPlanAdapter(db)
	subscriptionDatabasePort := postgres.NewSubscriptionAdapter(db)
	usageRecordDatabasePort := postgres.NewUsageRecordAdapter(db)
	quotaCachePort := ProvideQuotaCache(universalClient)
	billingDomain := ProvideBillingDomain(planDatabasePort, subscriptionDatabasePort, usageRecordDatabasePort, quotaCachePort, logger)
	orderDatabasePort := postgres.NewOrderAdapter(db)
	orderItemDatabasePort := postgres.NewOrderItemAdapter(db)
	invoiceDatabasePort := postgres.NewInvoiceAdapter(db)
	orderDomain := ProvideOrderDomain(orderDatabasePort, orderItemDatabasePort, invoiceDatabasePort, planDatabasePort, logger)
	paymentDatabasePort := postgres.NewPaymentAdapter(db)
	webhookEventDatabasePort := postgres.NewWebhookEventAdapter(db)
	orderReaderPort := ProvideOrderReaderAdapter(orderDomain)
	billingReaderPort := ProvideBillingReaderAdapter(billingDomain)
	eventPublisherPort := ProvideEventPublisher()
	paymentDomain := ProvidePaymentDomain(paymentDatabasePort, webhookEventDatabasePort, orderReaderPort, billingReaderPort, eventPublisherPort, cfg, logger)
	aiProviderDatabasePort := postgres.NewAIProviderAdapter(db)
	aiModelDatabasePort := postgres.NewAIModelAdapter(db)
	aiProviderAccountDatabasePort := postgres.NewAIProviderAccountAdapter(db)
	aiModelGroupDatabasePort := postgres.NewAIModelGroupAdapter(db)
	aiProviderHealthCachePort := ProvideAIHealthCache(universalClient)
	aiEmbeddingCachePort := ProvideAIEmbeddingCache(universalClient)
	aiVendorRegistryPort := ProvideVendorRegistry(client)
	aiCryptoPort := ProvideAICryptoAdapter(cfg)
	aiDomain := ProvideAIDomain(aiProviderDatabasePort, aiModelDatabasePort, aiProviderAccountDatabasePort, aiModelGroupDatabasePort, aiProviderHealthCachePort, aiEmbeddingCachePort, aiVendorRegistryPort, aiCryptoPort, logger)
	gitRepoDatabaseAdapter := postgres.NewGitRepoDatabaseAdapter(db)
	gitCollaboratorDatabaseAdapter := postgres.NewGitCollaboratorDatabaseAdapter(db)
	gitPullRequestDatabaseAdapter := postgres.NewGitPullRequestDatabaseAdapter(db)
	gitLFSObjectDatabaseAdapter := postgres.NewGitLFSObjectDatabaseAdapter(db)
	gitLFSLockDatabaseAdapter := postgres.NewGitLFSLockDatabaseAdapter(db)
	gitDomain := ProvideGitDomain(gitRepoDatabaseAdapter, gitCollaboratorDatabaseAdapter, gitPullRequestDatabaseAdapter, gitLFSObjectDatabaseAdapter, gitLFSLockDatabaseAdapter, cfg, logger)
	teamAdapter := postgres.NewTeamAdapter(db)
	teamMemberAdapter := postgres.NewTeamMemberAdapter(db)
	teamInvitationAdapter := postgres.NewTeamInvitationAdapter(db)
	collaborationUserLookupAdapter := postgres.NewCollaborationUserLookupAdapter(db)
	collaborationTransactionAdapter := postgres.NewCollaborationTransactionAdapter(db)
	collaborationDomain := ProvideCollaborationDomain(teamAdapter, teamMemberAdapter, teamInvitationAdapter, collaborationUserLookupAdapter, collaborationTransactionAdapter, cfg, logger)
	mediaProviderDBAdapter := postgres.NewMediaProviderDBAdapter(db)
	mediaModelDBAdapter := postgres.NewMediaModelDBAdapter(db)
	mediaTaskDBAdapter := postgres.NewMediaTaskDBAdapter(db)
	mediaProviderHealthCachePort := ProvideMediaHealthCache(universalClient)
	mediaVendorRegistryPort := ProvideMediaVendorRegistry(client)
	mediaCryptoPort := ProvideMediaCryptoAdapter(cfg)
	mediaDomain := ProvideMediaDomain(mediaProviderDBAdapter, mediaModelDBAdapter, mediaTaskDBAdapter, mediaProviderHealthCachePort, mediaVendorRegistryPort, mediaCryptoPort, logger)
	chatHandler := ai.NewChatHandler(aiDomain)
	providerAdminHandler := ProvideAIProviderAdminHandler(aiDomain)
	modelAdminHandler := ProvideAIModelAdminHandler(aiDomain)
	publicHandler := ProvideAIPublicHandler(aiDomain)
	handler := pingproto.NewHandler()
	authprotoHandler := authproto.NewHandler(authDomain)
	userprotoHandler := userproto.NewHandler(userDomain)
	orderprotoHandler := orderproto.NewHandler(orderDomain)
	billingprotoHandler := billingproto.NewHandler(billingDomain)
	aiprotoHandler := ProvideAIProtoHandler(chatHandler, providerAdminHandler, modelAdminHandler, publicHandler)
	collabhttpHandler := ProvideCollaborationHandler(collaborationDomain, cfg)
	collaborationprotoHandler := ProvideCollaborationProtoHandler(collabhttpHandler)
	paymentHandler := paymenthttp.NewPaymentHandler(paymentDomain)
	refundHandler := paymenthttp.NewRefundHandler(paymentDomain)
	webhookHandler := paymenthttp.NewWebhookHandler(paymentDomain)
	paymentprotoHandler := ProvidePaymentProtoHandler(paymentHandler, refundHandler, webhookHandler)
	githttpHandler := ProvideGitHandler(gitDomain, cfg)
	gitprotoHandler := ProvideGitProtoHandler(githttpHandler)
	mediahttpHandler := ProvideMediaHandler(mediaDomain)
	mediaprotoHandler := ProvideMediaProtoHandler(mediahttpHandler)
	subscriptionHandler := billinghttp.NewSubscriptionHandler(billingDomain)
	quotaHandler := billinghttp.NewQuotaHandler(billingDomain)
	creditsHandler := billinghttp.NewCreditsHandler(billingDomain)
	usageHandler := billinghttp.NewUsageHandler(billingDomain)
	dependencies := &Dependencies{
		Config:                    cfg,
		DB:                        db,
		Redis:                     universalClient,
		HTTPClient:                client,
		RateLimiter:               rateLimiterPort,
		Logger:                    loggerLogger,
		ZapLogger:                 logger,
		Metrics:                   metrics,
		UserDomain:                userDomain,
		AuthDomain:                authDomain,
		BillingDomain:             billingDomain,
		OrderDomain:               orderDomain,
		PaymentDomain:             paymentDomain,
		AIDomain:                  aiDomain,
		GitDomain:                 gitDomain,
		CollaborationDomain:       collaborationDomain,
		MediaDomain:               mediaDomain,
		AIChatHandler:             chatHandler,
		AIProviderAdminHandler:    providerAdminHandler,
		AIModelAdminHandler:       modelAdminHandler,
		AIPublicHandler:           publicHandler,
		PingProtoHandler:          handler,
		AuthProtoHandler:          authprotoHandler,
		UserProtoHandler:          userprotoHandler,
		OrderProtoHandler:         orderprotoHandler,
		BillingProtoHandler:       billingprotoHandler,
		AIProtoHandler:            aiprotoHandler,
		CollaborationProtoHandler: collaborationprotoHandler,
		PaymentProtoHandler:       paymentprotoHandler,
		GitProtoHandler:           gitprotoHandler,
		MediaProtoHandler:         mediaprotoHandler,
		SubscriptionHandler:       subscriptionHandler,
		QuotaHandler:              quotaHandler,
		CreditsHandler:            creditsHandler,
		UsageHandler:              usageHandler,
		PaymentHandler:            paymentHandler,
		RefundHandler:             refundHandler,
		WebhookHandler:            webhookHandler,
		GitHandler:                githttpHandler,
		CollaborationHandler:      collabhttpHandler,
		MediaHandler:              mediahttpHandler,
	}
	return dependencies, func() {
	}, nil
}

// wire.go:

// Dependencies holds all injected dependencies.
type Dependencies struct {
	Config      *config.Config
	DB          *gorm.DB
	Redis       redis.UniversalClient
	HTTPClient  *http.Client
	RateLimiter outbound.RateLimiterPort
	Logger      *logger.Logger
	ZapLogger   *zap.Logger
	Metrics     *metrics.Metrics

	// Domains
	UserDomain          user.UserDomain
	AuthDomain          auth.AuthDomain
	BillingDomain       billing.BillingDomain
	OrderDomain         order.OrderDomain
	PaymentDomain       payment.PaymentDomain
	AIDomain            ai2.AIDomain
	GitDomain           inbound.GitDomain
	CollaborationDomain inbound.CollaborationDomain
	MediaDomain         inbound.MediaDomain

	// AI HTTP Handlers
	AIChatHandler          *ai.ChatHandler
	AIProviderAdminHandler *ai.ProviderAdminHandler
	AIModelAdminHandler    *ai.ModelAdminHandler
	AIPublicHandler        *ai.PublicHandler

	// Proto-defined HTTP Handlers (generated from google.api.http)
	PingProtoHandler          *pingproto.Handler
	AuthProtoHandler          *authproto.Handler
	UserProtoHandler          *userproto.Handler
	OrderProtoHandler         *orderproto.Handler
	BillingProtoHandler       *billingproto.Handler
	AIProtoHandler            *aiproto.Handler
	CollaborationProtoHandler *collaborationproto.Handler
	PaymentProtoHandler       *paymentproto.Handler
	GitProtoHandler           *gitproto.Handler
	MediaProtoHandler         *mediaproto.Handler

	// Billing HTTP Handlers
	SubscriptionHandler *billinghttp.SubscriptionHandler
	QuotaHandler        *billinghttp.QuotaHandler
	CreditsHandler      *billinghttp.CreditsHandler
	UsageHandler        *billinghttp.UsageHandler

	// Payment HTTP Handlers
	PaymentHandler *paymenthttp.PaymentHandler
	RefundHandler  *paymenthttp.RefundHandler
	WebhookHandler *paymenthttp.WebhookHandler

	// Git HTTP Handlers
	GitHandler *githttp.Handler

	// Collaboration HTTP Handlers
	CollaborationHandler *collabhttp.Handler

	// Media HTTP Handlers
	MediaHandler *mediahttp.Handler
}
