// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: payment/payment.proto

package paymentv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	common "github.com/uniedit/server/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreatePaymentIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentIntentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type PaymentIntentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	ClientSecret    string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Amount          int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentIntentResponse) Reset() {
	*x = PaymentIntentResponse{}
	mi := &file_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentIntentResponse) ProtoMessage() {}

func (x *PaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*PaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentIntentResponse) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *PaymentIntentResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *PaymentIntentResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentIntentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateNativePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Scene         string                 `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,4,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	Openid        string                 `protobuf:"bytes,5,opt,name=openid,proto3" json:"openid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNativePaymentRequest) Reset() {
	*x = CreateNativePaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNativePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNativePaymentRequest) ProtoMessage() {}

func (x *CreateNativePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNativePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreateNativePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNativePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateNativePaymentRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreateNativePaymentRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *CreateNativePaymentRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *CreateNativePaymentRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

type NativePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	PayUrl        string                 `protobuf:"bytes,4,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	QrCode        string                 `protobuf:"bytes,5,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	AppPayData    string                 `protobuf:"bytes,6,opt,name=app_pay_data,json=appPayData,proto3" json:"app_pay_data,omitempty"`
	MiniPayData   map[string]string      `protobuf:"bytes,7,rep,name=mini_pay_data,json=miniPayData,proto3" json:"mini_pay_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Amount        int64                  `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,10,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NativePaymentResponse) Reset() {
	*x = NativePaymentResponse{}
	mi := &file_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativePaymentResponse) ProtoMessage() {}

func (x *NativePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativePaymentResponse.ProtoReflect.Descriptor instead.
func (*NativePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *NativePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *NativePaymentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *NativePaymentResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *NativePaymentResponse) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *NativePaymentResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

func (x *NativePaymentResponse) GetAppPayData() string {
	if x != nil {
		return x.AppPayData
	}
	return ""
}

func (x *NativePaymentResponse) GetMiniPayData() map[string]string {
	if x != nil {
		return x.MiniPayData
	}
	return nil
}

func (x *NativePaymentResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NativePaymentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *NativePaymentResponse) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type Payment struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId               string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId                string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount                int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency              string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Method                string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Status                string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Provider              string                 `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	StripePaymentIntentId string                 `protobuf:"bytes,9,opt,name=stripe_payment_intent_id,json=stripePaymentIntentId,proto3" json:"stripe_payment_intent_id,omitempty"`
	StripeChargeId        string                 `protobuf:"bytes,10,opt,name=stripe_charge_id,json=stripeChargeId,proto3" json:"stripe_charge_id,omitempty"`
	TradeNo               string                 `protobuf:"bytes,11,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	PayerId               string                 `protobuf:"bytes,12,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	FailureCode           string                 `protobuf:"bytes,13,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	FailureMessage        string                 `protobuf:"bytes,14,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	RefundedAmount        int64                  `protobuf:"varint,15,opt,name=refunded_amount,json=refundedAmount,proto3" json:"refunded_amount,omitempty"`
	SucceededAt           string                 `protobuf:"bytes,16,opt,name=succeeded_at,json=succeededAt,proto3" json:"succeeded_at,omitempty"`
	FailedAt              string                 `protobuf:"bytes,17,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	CreatedAt             string                 `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             string                 `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Payment) GetStripePaymentIntentId() string {
	if x != nil {
		return x.StripePaymentIntentId
	}
	return ""
}

func (x *Payment) GetStripeChargeId() string {
	if x != nil {
		return x.StripeChargeId
	}
	return ""
}

func (x *Payment) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *Payment) GetPayerId() string {
	if x != nil {
		return x.PayerId
	}
	return ""
}

func (x *Payment) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *Payment) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *Payment) GetRefundedAmount() int64 {
	if x != nil {
		return x.RefundedAmount
	}
	return 0
}

func (x *Payment) GetSucceededAt() string {
	if x != nil {
		return x.SucceededAt
	}
	return ""
}

func (x *Payment) GetFailedAt() string {
	if x != nil {
		return x.FailedAt
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Payment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ListPaymentsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ListPaymentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListPaymentsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ListPaymentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Payment             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_payment_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{7}
}

func (x *ListPaymentsResponse) GetData() []*Payment {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPaymentsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPaymentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPaymentsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type PaymentMethodInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CardBrand     string                 `protobuf:"bytes,3,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	CardLast4     string                 `protobuf:"bytes,4,opt,name=card_last4,json=cardLast4,proto3" json:"card_last4,omitempty"`
	ExpMonth      int32                  `protobuf:"varint,5,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear       int32                  `protobuf:"varint,6,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentMethodInfo) Reset() {
	*x = PaymentMethodInfo{}
	mi := &file_payment_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethodInfo) ProtoMessage() {}

func (x *PaymentMethodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethodInfo.ProtoReflect.Descriptor instead.
func (*PaymentMethodInfo) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentMethodInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentMethodInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PaymentMethodInfo) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *PaymentMethodInfo) GetCardLast4() string {
	if x != nil {
		return x.CardLast4
	}
	return ""
}

func (x *PaymentMethodInfo) GetExpMonth() int32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *PaymentMethodInfo) GetExpYear() int32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *PaymentMethodInfo) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type ListPaymentMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []*PaymentMethodInfo   `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentMethodsResponse) Reset() {
	*x = ListPaymentMethodsResponse{}
	mi := &file_payment_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentMethodsResponse) ProtoMessage() {}

func (x *ListPaymentMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentMethodsResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{9}
}

func (x *ListPaymentMethodsResponse) GetMethods() []*PaymentMethodInfo {
	if x != nil {
		return x.Methods
	}
	return nil
}

type CreateRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRefundRequest) Reset() {
	*x = CreateRefundRequest{}
	mi := &file_payment_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundRequest) ProtoMessage() {}

func (x *CreateRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundRequest.ProtoReflect.Descriptor instead.
func (*CreateRefundRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRefundRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateRefundRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateRefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StripeWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StripeWebhookResponse) Reset() {
	*x = StripeWebhookResponse{}
	mi := &file_payment_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StripeWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StripeWebhookResponse) ProtoMessage() {}

func (x *StripeWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StripeWebhookResponse.ProtoReflect.Descriptor instead.
func (*StripeWebhookResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{11}
}

func (x *StripeWebhookResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type WechatWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatWebhookResponse) Reset() {
	*x = WechatWebhookResponse{}
	mi := &file_payment_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatWebhookResponse) ProtoMessage() {}

func (x *WechatWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatWebhookResponse.ProtoReflect.Descriptor instead.
func (*WechatWebhookResponse) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{12}
}

func (x *WechatWebhookResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WechatWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_payment_payment_proto protoreflect.FileDescriptor

const file_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x15payment/payment.proto\x12\x12uniedit.payment.v1\x1a\x13common/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x1aCreatePaymentIntentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x9c\x01\n" +
	"\x15PaymentIntentResponse\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\x9c\x01\n" +
	"\x1aCreateNativePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x14\n" +
	"\x05scene\x18\x03 \x01(\tR\x05scene\x12\x1d\n" +
	"\n" +
	"return_url\x18\x04 \x01(\tR\treturnUrl\x12\x16\n" +
	"\x06openid\x18\x05 \x01(\tR\x06openid\"\xb2\x03\n" +
	"\x15NativePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x17\n" +
	"\apay_url\x18\x04 \x01(\tR\x06payUrl\x12\x17\n" +
	"\aqr_code\x18\x05 \x01(\tR\x06qrCode\x12 \n" +
	"\fapp_pay_data\x18\x06 \x01(\tR\n" +
	"appPayData\x12^\n" +
	"\rmini_pay_data\x18\a \x03(\v2:.uniedit.payment.v1.NativePaymentResponse.MiniPayDataEntryR\vminiPayData\x12\x16\n" +
	"\x06amount\x18\b \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12\x1f\n" +
	"\vexpire_time\x18\n" +
	" \x01(\x03R\n" +
	"expireTime\x1a>\n" +
	"\x10MiniPayDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x04\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1a\n" +
	"\bprovider\x18\b \x01(\tR\bprovider\x127\n" +
	"\x18stripe_payment_intent_id\x18\t \x01(\tR\x15stripePaymentIntentId\x12(\n" +
	"\x10stripe_charge_id\x18\n" +
	" \x01(\tR\x0estripeChargeId\x12\x19\n" +
	"\btrade_no\x18\v \x01(\tR\atradeNo\x12\x19\n" +
	"\bpayer_id\x18\f \x01(\tR\apayerId\x12!\n" +
	"\ffailure_code\x18\r \x01(\tR\vfailureCode\x12'\n" +
	"\x0ffailure_message\x18\x0e \x01(\tR\x0efailureMessage\x12'\n" +
	"\x0frefunded_amount\x18\x0f \x01(\x03R\x0erefundedAmount\x12!\n" +
	"\fsucceeded_at\x18\x10 \x01(\tR\vsucceededAt\x12\x1b\n" +
	"\tfailed_at\x18\x11 \x01(\tR\bfailedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x12 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\tR\tupdatedAt\"\x95\x01\n" +
	"\x13ListPaymentsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xaf\x01\n" +
	"\x14ListPaymentsResponse\x12/\n" +
	"\x04data\x18\x01 \x03(\v2\x1b.uniedit.payment.v1.PaymentR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\xcc\x01\n" +
	"\x11PaymentMethodInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x03 \x01(\tR\tcardBrand\x12\x1d\n" +
	"\n" +
	"card_last4\x18\x04 \x01(\tR\tcardLast4\x12\x1b\n" +
	"\texp_month\x18\x05 \x01(\x05R\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x06 \x01(\x05R\aexpYear\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\"]\n" +
	"\x1aListPaymentMethodsResponse\x12?\n" +
	"\amethods\x18\x01 \x03(\v2%.uniedit.payment.v1.PaymentMethodInfoR\amethods\"U\n" +
	"\x13CreateRefundRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"3\n" +
	"\x15StripeWebhookResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"E\n" +
	"\x15WechatWebhookResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x88\x05\n" +
	"\x0ePaymentService\x12\x8d\x01\n" +
	"\x13CreatePaymentIntent\x12..uniedit.payment.v1.CreatePaymentIntentRequest\x1a).uniedit.payment.v1.PaymentIntentResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/payments/intent\x12\x8d\x01\n" +
	"\x13CreateNativePayment\x12..uniedit.payment.v1.CreateNativePaymentRequest\x1a).uniedit.payment.v1.NativePaymentResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/payments/native\x12e\n" +
	"\n" +
	"GetPayment\x12\".uniedit.payment.v1.GetByIDRequest\x1a\x1b.uniedit.payment.v1.Payment\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/payments/{id}\x12t\n" +
	"\fListPayments\x12'.uniedit.payment.v1.ListPaymentsRequest\x1a(.uniedit.payment.v1.ListPaymentsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/payments\x12y\n" +
	"\x12ListPaymentMethods\x12\x18.uniedit.common.v1.Empty\x1a..uniedit.payment.v1.ListPaymentMethodsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/payments/methods2\x94\x01\n" +
	"\x13PaymentAdminService\x12}\n" +
	"\fCreateRefund\x12'.uniedit.payment.v1.CreateRefundRequest\x1a\".uniedit.common.v1.MessageResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/payments/{id}/refund2\xcf\x02\n" +
	"\x0eWebhookService\x12n\n" +
	"\rStripeWebhook\x12\x18.uniedit.common.v1.Empty\x1a).uniedit.payment.v1.StripeWebhookResponse\"\x18\x82\xd3\xe4\x93\x02\x12\"\x10/webhooks/stripe\x12]\n" +
	"\rAlipayWebhook\x12\x18.uniedit.common.v1.Empty\x1a\x18.uniedit.common.v1.Empty\"\x18\x82\xd3\xe4\x93\x02\x12\"\x10/webhooks/alipay\x12n\n" +
	"\rWechatWebhook\x12\x18.uniedit.common.v1.Empty\x1a).uniedit.payment.v1.WechatWebhookResponse\"\x18\x82\xd3\xe4\x93\x02\x12\"\x10/webhooks/wechatB\x9e\x01\x92Ag\x12I\n" +
	"\vUniEdit API\x126UniEdit 后端 API（由 proto 自动生成 OpenAPI）2\x02v1\x1a\x0elocalhost:8080\"\a/api/v1*\x01\x01Z2github.com/uniedit/server/api/pb/payment;paymentv1b\x06proto3"

var (
	file_payment_payment_proto_rawDescOnce sync.Once
	file_payment_payment_proto_rawDescData []byte
)

func file_payment_payment_proto_rawDescGZIP() []byte {
	file_payment_payment_proto_rawDescOnce.Do(func() {
		file_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)))
	})
	return file_payment_payment_proto_rawDescData
}

var file_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_payment_payment_proto_goTypes = []any{
	(*GetByIDRequest)(nil),             // 0: uniedit.payment.v1.GetByIDRequest
	(*CreatePaymentIntentRequest)(nil), // 1: uniedit.payment.v1.CreatePaymentIntentRequest
	(*PaymentIntentResponse)(nil),      // 2: uniedit.payment.v1.PaymentIntentResponse
	(*CreateNativePaymentRequest)(nil), // 3: uniedit.payment.v1.CreateNativePaymentRequest
	(*NativePaymentResponse)(nil),      // 4: uniedit.payment.v1.NativePaymentResponse
	(*Payment)(nil),                    // 5: uniedit.payment.v1.Payment
	(*ListPaymentsRequest)(nil),        // 6: uniedit.payment.v1.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),       // 7: uniedit.payment.v1.ListPaymentsResponse
	(*PaymentMethodInfo)(nil),          // 8: uniedit.payment.v1.PaymentMethodInfo
	(*ListPaymentMethodsResponse)(nil), // 9: uniedit.payment.v1.ListPaymentMethodsResponse
	(*CreateRefundRequest)(nil),        // 10: uniedit.payment.v1.CreateRefundRequest
	(*StripeWebhookResponse)(nil),      // 11: uniedit.payment.v1.StripeWebhookResponse
	(*WechatWebhookResponse)(nil),      // 12: uniedit.payment.v1.WechatWebhookResponse
	nil,                                // 13: uniedit.payment.v1.NativePaymentResponse.MiniPayDataEntry
	(*common.Empty)(nil),               // 14: uniedit.common.v1.Empty
	(*common.MessageResponse)(nil),     // 15: uniedit.common.v1.MessageResponse
}
var file_payment_payment_proto_depIdxs = []int32{
	13, // 0: uniedit.payment.v1.NativePaymentResponse.mini_pay_data:type_name -> uniedit.payment.v1.NativePaymentResponse.MiniPayDataEntry
	5,  // 1: uniedit.payment.v1.ListPaymentsResponse.data:type_name -> uniedit.payment.v1.Payment
	8,  // 2: uniedit.payment.v1.ListPaymentMethodsResponse.methods:type_name -> uniedit.payment.v1.PaymentMethodInfo
	1,  // 3: uniedit.payment.v1.PaymentService.CreatePaymentIntent:input_type -> uniedit.payment.v1.CreatePaymentIntentRequest
	3,  // 4: uniedit.payment.v1.PaymentService.CreateNativePayment:input_type -> uniedit.payment.v1.CreateNativePaymentRequest
	0,  // 5: uniedit.payment.v1.PaymentService.GetPayment:input_type -> uniedit.payment.v1.GetByIDRequest
	6,  // 6: uniedit.payment.v1.PaymentService.ListPayments:input_type -> uniedit.payment.v1.ListPaymentsRequest
	14, // 7: uniedit.payment.v1.PaymentService.ListPaymentMethods:input_type -> uniedit.common.v1.Empty
	10, // 8: uniedit.payment.v1.PaymentAdminService.CreateRefund:input_type -> uniedit.payment.v1.CreateRefundRequest
	14, // 9: uniedit.payment.v1.WebhookService.StripeWebhook:input_type -> uniedit.common.v1.Empty
	14, // 10: uniedit.payment.v1.WebhookService.AlipayWebhook:input_type -> uniedit.common.v1.Empty
	14, // 11: uniedit.payment.v1.WebhookService.WechatWebhook:input_type -> uniedit.common.v1.Empty
	2,  // 12: uniedit.payment.v1.PaymentService.CreatePaymentIntent:output_type -> uniedit.payment.v1.PaymentIntentResponse
	4,  // 13: uniedit.payment.v1.PaymentService.CreateNativePayment:output_type -> uniedit.payment.v1.NativePaymentResponse
	5,  // 14: uniedit.payment.v1.PaymentService.GetPayment:output_type -> uniedit.payment.v1.Payment
	7,  // 15: uniedit.payment.v1.PaymentService.ListPayments:output_type -> uniedit.payment.v1.ListPaymentsResponse
	9,  // 16: uniedit.payment.v1.PaymentService.ListPaymentMethods:output_type -> uniedit.payment.v1.ListPaymentMethodsResponse
	15, // 17: uniedit.payment.v1.PaymentAdminService.CreateRefund:output_type -> uniedit.common.v1.MessageResponse
	11, // 18: uniedit.payment.v1.WebhookService.StripeWebhook:output_type -> uniedit.payment.v1.StripeWebhookResponse
	14, // 19: uniedit.payment.v1.WebhookService.AlipayWebhook:output_type -> uniedit.common.v1.Empty
	12, // 20: uniedit.payment.v1.WebhookService.WechatWebhook:output_type -> uniedit.payment.v1.WechatWebhookResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_payment_payment_proto_init() }
func file_payment_payment_proto_init() {
	if File_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_payment_payment_proto_goTypes,
		DependencyIndexes: file_payment_payment_proto_depIdxs,
		MessageInfos:      file_payment_payment_proto_msgTypes,
	}.Build()
	File_payment_payment_proto = out.File
	file_payment_payment_proto_goTypes = nil
	file_payment_payment_proto_depIdxs = nil
}
