// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: ai/ai.proto

package aiv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	common "github.com/uniedit/server/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_ai_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Model         string                  `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*ChatMessage          `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxTokens     int32                   `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   *wrapperspb.DoubleValue `protobuf:"bytes,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP          *wrapperspb.DoubleValue `protobuf:"bytes,5,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	Stop          []string                `protobuf:"bytes,6,rep,name=stop,proto3" json:"stop,omitempty"`
	Tools         []*Tool                 `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	ToolChoice    *structpb.Value         `protobuf:"bytes,8,opt,name=tool_choice,json=toolChoice,proto3" json:"tool_choice,omitempty"`
	Stream        bool                    `protobuf:"varint,9,opt,name=stream,proto3" json:"stream,omitempty"`
	Metadata      *structpb.Struct        `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_ai_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatRequest) GetTemperature() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Temperature
	}
	return nil
}

func (x *ChatRequest) GetTopP() *wrapperspb.DoubleValue {
	if x != nil {
		return x.TopP
	}
	return nil
}

func (x *ChatRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *ChatRequest) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatRequest) GetToolChoice() *structpb.Value {
	if x != nil {
		return x.ToolChoice
	}
	return nil
}

func (x *ChatRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ChatRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       *structpb.Value        `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,4,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_ai_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() *structpb.Value {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ChatMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ChatMessage) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Function      *FunctionDef           `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_ai_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{3}
}

func (x *Tool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tool) GetFunction() *FunctionDef {
	if x != nil {
		return x.Function
	}
	return nil
}

type FunctionDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDef) Reset() {
	*x = FunctionDef{}
	mi := &file_ai_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDef) ProtoMessage() {}

func (x *FunctionDef) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDef.ProtoReflect.Descriptor instead.
func (*FunctionDef) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDef) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function      *FunctionCall          `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_ai_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCall) GetFunction() *FunctionCall {
	if x != nil {
		return x.Function
	}
	return nil
}

type FunctionCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_ai_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{6}
}

func (x *FunctionCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_ai_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{7}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type RoutingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderUsed  string                 `protobuf:"bytes,1,opt,name=provider_used,json=providerUsed,proto3" json:"provider_used,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	CostUsd       float64                `protobuf:"fixed64,4,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingInfo) Reset() {
	*x = RoutingInfo{}
	mi := &file_ai_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingInfo) ProtoMessage() {}

func (x *RoutingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingInfo.ProtoReflect.Descriptor instead.
func (*RoutingInfo) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{8}
}

func (x *RoutingInfo) GetProviderUsed() string {
	if x != nil {
		return x.ProviderUsed
	}
	return ""
}

func (x *RoutingInfo) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *RoutingInfo) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RoutingInfo) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Message       *ChatMessage           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	FinishReason  string                 `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	Routing       *RoutingInfo           `protobuf:"bytes,6,opt,name=routing,proto3" json:"routing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_ai_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{9}
}

func (x *ChatResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ChatResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatResponse) GetRouting() *RoutingInfo {
	if x != nil {
		return x.Routing
	}
	return nil
}

type RateLimitConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rpm           int32                  `protobuf:"varint,1,opt,name=rpm,proto3" json:"rpm,omitempty"`
	Tpm           int32                  `protobuf:"varint,2,opt,name=tpm,proto3" json:"tpm,omitempty"`
	DailyLimit    int32                  `protobuf:"varint,3,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitConfig) Reset() {
	*x = RateLimitConfig{}
	mi := &file_ai_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitConfig) ProtoMessage() {}

func (x *RateLimitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitConfig.ProtoReflect.Descriptor instead.
func (*RateLimitConfig) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{10}
}

func (x *RateLimitConfig) GetRpm() int32 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

func (x *RateLimitConfig) GetTpm() int32 {
	if x != nil {
		return x.Tpm
	}
	return 0
}

func (x *RateLimitConfig) GetDailyLimit() int32 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Weight        int32                  `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	RateLimit     *RateLimitConfig       `protobuf:"bytes,8,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Options       *structpb.Struct       `protobuf:"bytes,9,opt,name=options,proto3" json:"options,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_ai_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{11}
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Provider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Provider) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Provider) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Provider) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Provider) GetRateLimit() *RateLimitConfig {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *Provider) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Provider) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Provider) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Data          []*Provider            `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_ai_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{12}
}

func (x *ListProvidersResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ListProvidersResponse) GetData() []*Provider {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	RateLimit     *RateLimitConfig       `protobuf:"bytes,5,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Options       *structpb.Struct       `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	Weight        int32                  `protobuf:"varint,7,opt,name=weight,proto3" json:"weight,omitempty"`
	Priority      int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	Enabled       bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderRequest) Reset() {
	*x = CreateProviderRequest{}
	mi := &file_ai_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderRequest) ProtoMessage() {}

func (x *CreateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateProviderRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{13}
}

func (x *CreateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProviderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateProviderRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CreateProviderRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateProviderRequest) GetRateLimit() *RateLimitConfig {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *CreateProviderRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateProviderRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateProviderRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateProviderRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *common.StringValue    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BaseUrl       *common.StringValue    `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        *common.StringValue    `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	RateLimit     *RateLimitConfig       `protobuf:"bytes,5,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Options       *structpb.Struct       `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	Weight        *common.Int32Value     `protobuf:"bytes,7,opt,name=weight,proto3" json:"weight,omitempty"`
	Priority      *common.Int32Value     `protobuf:"bytes,8,opt,name=priority,proto3" json:"priority,omitempty"`
	Enabled       *common.BoolValue      `protobuf:"bytes,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderRequest) Reset() {
	*x = UpdateProviderRequest{}
	mi := &file_ai_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderRequest) ProtoMessage() {}

func (x *UpdateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateProviderRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProviderRequest) GetName() *common.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateProviderRequest) GetBaseUrl() *common.StringValue {
	if x != nil {
		return x.BaseUrl
	}
	return nil
}

func (x *UpdateProviderRequest) GetApiKey() *common.StringValue {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *UpdateProviderRequest) GetRateLimit() *RateLimitConfig {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *UpdateProviderRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *UpdateProviderRequest) GetWeight() *common.Int32Value {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *UpdateProviderRequest) GetPriority() *common.Int32Value {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *UpdateProviderRequest) GetEnabled() *common.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_ai_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type Model struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId       string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities     []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ContextWindow    int32                  `protobuf:"varint,5,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	MaxOutputTokens  int32                  `protobuf:"varint,6,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	InputCostPer_1K  float64                `protobuf:"fixed64,7,opt,name=input_cost_per_1k,json=inputCostPer1k,proto3" json:"input_cost_per_1k,omitempty"`
	OutputCostPer_1K float64                `protobuf:"fixed64,8,opt,name=output_cost_per_1k,json=outputCostPer1k,proto3" json:"output_cost_per_1k,omitempty"`
	Options          *structpb.Struct       `protobuf:"bytes,9,opt,name=options,proto3" json:"options,omitempty"`
	Enabled          bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_ai_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{16}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Model) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *Model) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *Model) GetInputCostPer_1K() float64 {
	if x != nil {
		return x.InputCostPer_1K
	}
	return 0
}

func (x *Model) GetOutputCostPer_1K() float64 {
	if x != nil {
		return x.OutputCostPer_1K
	}
	return 0
}

func (x *Model) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Model) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Model) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Model) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_ai_ai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{17}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type ListAllModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Data          []*Model               `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllModelsResponse) Reset() {
	*x = ListAllModelsResponse{}
	mi := &file_ai_ai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllModelsResponse) ProtoMessage() {}

func (x *ListAllModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllModelsResponse.ProtoReflect.Descriptor instead.
func (*ListAllModelsResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{18}
}

func (x *ListAllModelsResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ListAllModelsResponse) GetData() []*Model {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateModelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId       string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities     []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ContextWindow    int32                  `protobuf:"varint,5,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	MaxOutputTokens  int32                  `protobuf:"varint,6,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	InputCostPer_1K  float64                `protobuf:"fixed64,7,opt,name=input_cost_per_1k,json=inputCostPer1k,proto3" json:"input_cost_per_1k,omitempty"`
	OutputCostPer_1K float64                `protobuf:"fixed64,8,opt,name=output_cost_per_1k,json=outputCostPer1k,proto3" json:"output_cost_per_1k,omitempty"`
	Options          *structpb.Struct       `protobuf:"bytes,9,opt,name=options,proto3" json:"options,omitempty"`
	Enabled          bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_ai_ai_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{19}
}

func (x *CreateModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateModelRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CreateModelRequest) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *CreateModelRequest) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *CreateModelRequest) GetInputCostPer_1K() float64 {
	if x != nil {
		return x.InputCostPer_1K
	}
	return 0
}

func (x *CreateModelRequest) GetOutputCostPer_1K() float64 {
	if x != nil {
		return x.OutputCostPer_1K
	}
	return 0
}

func (x *CreateModelRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateModelRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateModelRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Id               string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             *common.StringValue     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities     *common.StringList      `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	ContextWindow    *common.Int32Value      `protobuf:"bytes,4,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	MaxOutputTokens  *common.Int32Value      `protobuf:"bytes,5,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	InputCostPer_1K  *wrapperspb.DoubleValue `protobuf:"bytes,6,opt,name=input_cost_per_1k,json=inputCostPer1k,proto3" json:"input_cost_per_1k,omitempty"`
	OutputCostPer_1K *wrapperspb.DoubleValue `protobuf:"bytes,7,opt,name=output_cost_per_1k,json=outputCostPer1k,proto3" json:"output_cost_per_1k,omitempty"`
	Options          *structpb.Struct        `protobuf:"bytes,8,opt,name=options,proto3" json:"options,omitempty"`
	Enabled          *common.BoolValue       `protobuf:"bytes,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateModelRequest) Reset() {
	*x = UpdateModelRequest{}
	mi := &file_ai_ai_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelRequest) ProtoMessage() {}

func (x *UpdateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateModelRequest) GetName() *common.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateModelRequest) GetCapabilities() *common.StringList {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *UpdateModelRequest) GetContextWindow() *common.Int32Value {
	if x != nil {
		return x.ContextWindow
	}
	return nil
}

func (x *UpdateModelRequest) GetMaxOutputTokens() *common.Int32Value {
	if x != nil {
		return x.MaxOutputTokens
	}
	return nil
}

func (x *UpdateModelRequest) GetInputCostPer_1K() *wrapperspb.DoubleValue {
	if x != nil {
		return x.InputCostPer_1K
	}
	return nil
}

func (x *UpdateModelRequest) GetOutputCostPer_1K() *wrapperspb.DoubleValue {
	if x != nil {
		return x.OutputCostPer_1K
	}
	return nil
}

func (x *UpdateModelRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *UpdateModelRequest) GetEnabled() *common.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

var File_ai_ai_proto protoreflect.FileDescriptor

const file_ai_ai_proto_rawDesc = "" +
	"\n" +
	"\vai/ai.proto\x12\runiedit.ai.v1\x1a\x13common/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb2\x03\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x126\n" +
	"\bmessages\x18\x02 \x03(\v2\x1a.uniedit.ai.v1.ChatMessageR\bmessages\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12>\n" +
	"\vtemperature\x18\x04 \x01(\v2\x1c.google.protobuf.DoubleValueR\vtemperature\x121\n" +
	"\x05top_p\x18\x05 \x01(\v2\x1c.google.protobuf.DoubleValueR\x04topP\x12\x12\n" +
	"\x04stop\x18\x06 \x03(\tR\x04stop\x12)\n" +
	"\x05tools\x18\a \x03(\v2\x13.uniedit.ai.v1.ToolR\x05tools\x127\n" +
	"\vtool_choice\x18\b \x01(\v2\x16.google.protobuf.ValueR\n" +
	"toolChoice\x12\x16\n" +
	"\x06stream\x18\t \x01(\bR\x06stream\x123\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xc1\x01\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x120\n" +
	"\acontent\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\acontent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\ftool_call_id\x18\x04 \x01(\tR\n" +
	"toolCallId\x126\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\x17.uniedit.ai.v1.ToolCallR\ttoolCalls\"R\n" +
	"\x04Tool\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x126\n" +
	"\bfunction\x18\x02 \x01(\v2\x1a.uniedit.ai.v1.FunctionDefR\bfunction\"|\n" +
	"\vFunctionDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"g\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x127\n" +
	"\bfunction\x18\x03 \x01(\v2\x1b.uniedit.ai.v1.FunctionCallR\bfunction\"@\n" +
	"\fFunctionCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"\x8b\x01\n" +
	"\vRoutingInfo\x12#\n" +
	"\rprovider_used\x18\x01 \x01(\tR\fproviderUsed\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x19\n" +
	"\bcost_usd\x18\x04 \x01(\x01R\acostUsd\"\xf1\x01\n" +
	"\fChatResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x124\n" +
	"\amessage\x18\x03 \x01(\v2\x1a.uniedit.ai.v1.ChatMessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason\x12*\n" +
	"\x05usage\x18\x05 \x01(\v2\x14.uniedit.ai.v1.UsageR\x05usage\x124\n" +
	"\arouting\x18\x06 \x01(\v2\x1a.uniedit.ai.v1.RoutingInfoR\arouting\"V\n" +
	"\x0fRateLimitConfig\x12\x10\n" +
	"\x03rpm\x18\x01 \x01(\x05R\x03rpm\x12\x10\n" +
	"\x03tpm\x18\x02 \x01(\x05R\x03tpm\x12\x1f\n" +
	"\vdaily_limit\x18\x03 \x01(\x05R\n" +
	"dailyLimit\"\xdb\x02\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x05R\x06weight\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12=\n" +
	"\n" +
	"rate_limit\x18\b \x01(\v2\x1e.uniedit.ai.v1.RateLimitConfigR\trateLimit\x121\n" +
	"\aoptions\x18\t \x01(\v2\x17.google.protobuf.StructR\aoptions\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"\\\n" +
	"\x15ListProvidersResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12+\n" +
	"\x04data\x18\x02 \x03(\v2\x17.uniedit.ai.v1.ProviderR\x04data\"\xb3\x02\n" +
	"\x15CreateProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12=\n" +
	"\n" +
	"rate_limit\x18\x05 \x01(\v2\x1e.uniedit.ai.v1.RateLimitConfigR\trateLimit\x121\n" +
	"\aoptions\x18\x06 \x01(\v2\x17.google.protobuf.StructR\aoptions\x12\x16\n" +
	"\x06weight\x18\a \x01(\x05R\x06weight\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\"\xeb\x03\n" +
	"\x15UpdateProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x04name\x18\x02 \x01(\v2\x1e.uniedit.common.v1.StringValueR\x04name\x129\n" +
	"\bbase_url\x18\x03 \x01(\v2\x1e.uniedit.common.v1.StringValueR\abaseUrl\x127\n" +
	"\aapi_key\x18\x04 \x01(\v2\x1e.uniedit.common.v1.StringValueR\x06apiKey\x12=\n" +
	"\n" +
	"rate_limit\x18\x05 \x01(\v2\x1e.uniedit.ai.v1.RateLimitConfigR\trateLimit\x121\n" +
	"\aoptions\x18\x06 \x01(\v2\x17.google.protobuf.StructR\aoptions\x125\n" +
	"\x06weight\x18\a \x01(\v2\x1d.uniedit.common.v1.Int32ValueR\x06weight\x129\n" +
	"\bpriority\x18\b \x01(\v2\x1d.uniedit.common.v1.Int32ValueR\bpriority\x126\n" +
	"\aenabled\x18\t \x01(\v2\x1c.uniedit.common.v1.BoolValueR\aenabled\"P\n" +
	"\x13HealthCheckResponse\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\"\xa6\x03\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12%\n" +
	"\x0econtext_window\x18\x05 \x01(\x05R\rcontextWindow\x12*\n" +
	"\x11max_output_tokens\x18\x06 \x01(\x05R\x0fmaxOutputTokens\x12)\n" +
	"\x11input_cost_per_1k\x18\a \x01(\x01R\x0einputCostPer1k\x12+\n" +
	"\x12output_cost_per_1k\x18\b \x01(\x01R\x0foutputCostPer1k\x121\n" +
	"\aoptions\x18\t \x01(\v2\x17.google.protobuf.StructR\aoptions\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"B\n" +
	"\x12ListModelsResponse\x12,\n" +
	"\x06models\x18\x01 \x03(\v2\x14.uniedit.ai.v1.ModelR\x06models\"Y\n" +
	"\x15ListAllModelsResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12(\n" +
	"\x04data\x18\x02 \x03(\v2\x14.uniedit.ai.v1.ModelR\x04data\"\xf5\x02\n" +
	"\x12CreateModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12%\n" +
	"\x0econtext_window\x18\x05 \x01(\x05R\rcontextWindow\x12*\n" +
	"\x11max_output_tokens\x18\x06 \x01(\x05R\x0fmaxOutputTokens\x12)\n" +
	"\x11input_cost_per_1k\x18\a \x01(\x01R\x0einputCostPer1k\x12+\n" +
	"\x12output_cost_per_1k\x18\b \x01(\x01R\x0foutputCostPer1k\x121\n" +
	"\aoptions\x18\t \x01(\v2\x17.google.protobuf.StructR\aoptions\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\"\xab\x04\n" +
	"\x12UpdateModelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x04name\x18\x02 \x01(\v2\x1e.uniedit.common.v1.StringValueR\x04name\x12A\n" +
	"\fcapabilities\x18\x03 \x01(\v2\x1d.uniedit.common.v1.StringListR\fcapabilities\x12D\n" +
	"\x0econtext_window\x18\x04 \x01(\v2\x1d.uniedit.common.v1.Int32ValueR\rcontextWindow\x12I\n" +
	"\x11max_output_tokens\x18\x05 \x01(\v2\x1d.uniedit.common.v1.Int32ValueR\x0fmaxOutputTokens\x12G\n" +
	"\x11input_cost_per_1k\x18\x06 \x01(\v2\x1c.google.protobuf.DoubleValueR\x0einputCostPer1k\x12I\n" +
	"\x12output_cost_per_1k\x18\a \x01(\v2\x1c.google.protobuf.DoubleValueR\x0foutputCostPer1k\x121\n" +
	"\aoptions\x18\b \x01(\v2\x17.google.protobuf.StructR\aoptions\x126\n" +
	"\aenabled\x18\t \x01(\v2\x1c.uniedit.common.v1.BoolValueR\aenabled2\xfa\x02\n" +
	"\tAIService\x12T\n" +
	"\x04Chat\x12\x1a.uniedit.ai.v1.ChatRequest\x1a\x1b.uniedit.ai.v1.ChatResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/ai/chat\x12^\n" +
	"\n" +
	"ChatStream\x12\x1a.uniedit.ai.v1.ChatRequest\x1a\x18.uniedit.common.v1.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/ai/chat/stream\x12]\n" +
	"\n" +
	"ListModels\x12\x18.uniedit.common.v1.Empty\x1a!.uniedit.ai.v1.ListModelsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/ai/models\x12X\n" +
	"\bGetModel\x12\x1d.uniedit.ai.v1.GetByIDRequest\x1a\x14.uniedit.ai.v1.Model\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/ai/models/{id}2\xc8\n" +
	"\n" +
	"\x0eAIAdminService\x12l\n" +
	"\rListProviders\x12\x18.uniedit.common.v1.Empty\x1a$.uniedit.ai.v1.ListProvidersResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/admin/ai/providers\x12o\n" +
	"\x0eCreateProvider\x12$.uniedit.ai.v1.CreateProviderRequest\x1a\x17.uniedit.ai.v1.Provider\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/admin/ai/providers\x12g\n" +
	"\vGetProvider\x12\x1d.uniedit.ai.v1.GetByIDRequest\x1a\x17.uniedit.ai.v1.Provider\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/admin/ai/providers/{id}\x12t\n" +
	"\x0eUpdateProvider\x12$.uniedit.ai.v1.UpdateProviderRequest\x1a\x17.uniedit.ai.v1.Provider\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/admin/ai/providers/{id}\x12u\n" +
	"\x0eDeleteProvider\x12\x1d.uniedit.ai.v1.GetByIDRequest\x1a\".uniedit.common.v1.MessageResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/admin/ai/providers/{id}\x12v\n" +
	"\n" +
	"SyncModels\x12\x1d.uniedit.ai.v1.GetByIDRequest\x1a\".uniedit.common.v1.MessageResponse\"%\x82\xd3\xe4\x93\x02\x1f\"\x1d/admin/ai/providers/{id}/sync\x12y\n" +
	"\vHealthCheck\x12\x1d.uniedit.ai.v1.GetByIDRequest\x1a\".uniedit.ai.v1.HealthCheckResponse\"'\x82\xd3\xe4\x93\x02!\"\x1f/admin/ai/providers/{id}/health\x12i\n" +
	"\rListAllModels\x12\x18.uniedit.common.v1.Empty\x1a$.uniedit.ai.v1.ListAllModelsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/admin/ai/models\x12c\n" +
	"\vCreateModel\x12!.uniedit.ai.v1.CreateModelRequest\x1a\x14.uniedit.ai.v1.Model\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/admin/ai/models\x12c\n" +
	"\rGetAdminModel\x12\x1d.uniedit.ai.v1.GetByIDRequest\x1a\x14.uniedit.ai.v1.Model\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/admin/ai/models/{id}\x12h\n" +
	"\vUpdateModel\x12!.uniedit.ai.v1.UpdateModelRequest\x1a\x14.uniedit.ai.v1.Model\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/admin/ai/models/{id}\x12o\n" +
	"\vDeleteModel\x12\x1d.uniedit.ai.v1.GetByIDRequest\x1a\".uniedit.common.v1.MessageResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/admin/ai/models/{id}B\x94\x01\x92Ag\x12I\n" +
	"\vUniEdit API\x126UniEdit 后端 API（由 proto 自动生成 OpenAPI）2\x02v1\x1a\x0elocalhost:8080\"\a/api/v1*\x01\x01Z(github.com/uniedit/server/api/pb/ai;aiv1b\x06proto3"

var (
	file_ai_ai_proto_rawDescOnce sync.Once
	file_ai_ai_proto_rawDescData []byte
)

func file_ai_ai_proto_rawDescGZIP() []byte {
	file_ai_ai_proto_rawDescOnce.Do(func() {
		file_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_ai_proto_rawDesc), len(file_ai_ai_proto_rawDesc)))
	})
	return file_ai_ai_proto_rawDescData
}

var file_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_ai_ai_proto_goTypes = []any{
	(*GetByIDRequest)(nil),         // 0: uniedit.ai.v1.GetByIDRequest
	(*ChatRequest)(nil),            // 1: uniedit.ai.v1.ChatRequest
	(*ChatMessage)(nil),            // 2: uniedit.ai.v1.ChatMessage
	(*Tool)(nil),                   // 3: uniedit.ai.v1.Tool
	(*FunctionDef)(nil),            // 4: uniedit.ai.v1.FunctionDef
	(*ToolCall)(nil),               // 5: uniedit.ai.v1.ToolCall
	(*FunctionCall)(nil),           // 6: uniedit.ai.v1.FunctionCall
	(*Usage)(nil),                  // 7: uniedit.ai.v1.Usage
	(*RoutingInfo)(nil),            // 8: uniedit.ai.v1.RoutingInfo
	(*ChatResponse)(nil),           // 9: uniedit.ai.v1.ChatResponse
	(*RateLimitConfig)(nil),        // 10: uniedit.ai.v1.RateLimitConfig
	(*Provider)(nil),               // 11: uniedit.ai.v1.Provider
	(*ListProvidersResponse)(nil),  // 12: uniedit.ai.v1.ListProvidersResponse
	(*CreateProviderRequest)(nil),  // 13: uniedit.ai.v1.CreateProviderRequest
	(*UpdateProviderRequest)(nil),  // 14: uniedit.ai.v1.UpdateProviderRequest
	(*HealthCheckResponse)(nil),    // 15: uniedit.ai.v1.HealthCheckResponse
	(*Model)(nil),                  // 16: uniedit.ai.v1.Model
	(*ListModelsResponse)(nil),     // 17: uniedit.ai.v1.ListModelsResponse
	(*ListAllModelsResponse)(nil),  // 18: uniedit.ai.v1.ListAllModelsResponse
	(*CreateModelRequest)(nil),     // 19: uniedit.ai.v1.CreateModelRequest
	(*UpdateModelRequest)(nil),     // 20: uniedit.ai.v1.UpdateModelRequest
	(*wrapperspb.DoubleValue)(nil), // 21: google.protobuf.DoubleValue
	(*structpb.Value)(nil),         // 22: google.protobuf.Value
	(*structpb.Struct)(nil),        // 23: google.protobuf.Struct
	(*common.StringValue)(nil),     // 24: uniedit.common.v1.StringValue
	(*common.Int32Value)(nil),      // 25: uniedit.common.v1.Int32Value
	(*common.BoolValue)(nil),       // 26: uniedit.common.v1.BoolValue
	(*common.StringList)(nil),      // 27: uniedit.common.v1.StringList
	(*common.Empty)(nil),           // 28: uniedit.common.v1.Empty
	(*common.MessageResponse)(nil), // 29: uniedit.common.v1.MessageResponse
}
var file_ai_ai_proto_depIdxs = []int32{
	2,  // 0: uniedit.ai.v1.ChatRequest.messages:type_name -> uniedit.ai.v1.ChatMessage
	21, // 1: uniedit.ai.v1.ChatRequest.temperature:type_name -> google.protobuf.DoubleValue
	21, // 2: uniedit.ai.v1.ChatRequest.top_p:type_name -> google.protobuf.DoubleValue
	3,  // 3: uniedit.ai.v1.ChatRequest.tools:type_name -> uniedit.ai.v1.Tool
	22, // 4: uniedit.ai.v1.ChatRequest.tool_choice:type_name -> google.protobuf.Value
	23, // 5: uniedit.ai.v1.ChatRequest.metadata:type_name -> google.protobuf.Struct
	22, // 6: uniedit.ai.v1.ChatMessage.content:type_name -> google.protobuf.Value
	5,  // 7: uniedit.ai.v1.ChatMessage.tool_calls:type_name -> uniedit.ai.v1.ToolCall
	4,  // 8: uniedit.ai.v1.Tool.function:type_name -> uniedit.ai.v1.FunctionDef
	23, // 9: uniedit.ai.v1.FunctionDef.parameters:type_name -> google.protobuf.Struct
	6,  // 10: uniedit.ai.v1.ToolCall.function:type_name -> uniedit.ai.v1.FunctionCall
	2,  // 11: uniedit.ai.v1.ChatResponse.message:type_name -> uniedit.ai.v1.ChatMessage
	7,  // 12: uniedit.ai.v1.ChatResponse.usage:type_name -> uniedit.ai.v1.Usage
	8,  // 13: uniedit.ai.v1.ChatResponse.routing:type_name -> uniedit.ai.v1.RoutingInfo
	10, // 14: uniedit.ai.v1.Provider.rate_limit:type_name -> uniedit.ai.v1.RateLimitConfig
	23, // 15: uniedit.ai.v1.Provider.options:type_name -> google.protobuf.Struct
	11, // 16: uniedit.ai.v1.ListProvidersResponse.data:type_name -> uniedit.ai.v1.Provider
	10, // 17: uniedit.ai.v1.CreateProviderRequest.rate_limit:type_name -> uniedit.ai.v1.RateLimitConfig
	23, // 18: uniedit.ai.v1.CreateProviderRequest.options:type_name -> google.protobuf.Struct
	24, // 19: uniedit.ai.v1.UpdateProviderRequest.name:type_name -> uniedit.common.v1.StringValue
	24, // 20: uniedit.ai.v1.UpdateProviderRequest.base_url:type_name -> uniedit.common.v1.StringValue
	24, // 21: uniedit.ai.v1.UpdateProviderRequest.api_key:type_name -> uniedit.common.v1.StringValue
	10, // 22: uniedit.ai.v1.UpdateProviderRequest.rate_limit:type_name -> uniedit.ai.v1.RateLimitConfig
	23, // 23: uniedit.ai.v1.UpdateProviderRequest.options:type_name -> google.protobuf.Struct
	25, // 24: uniedit.ai.v1.UpdateProviderRequest.weight:type_name -> uniedit.common.v1.Int32Value
	25, // 25: uniedit.ai.v1.UpdateProviderRequest.priority:type_name -> uniedit.common.v1.Int32Value
	26, // 26: uniedit.ai.v1.UpdateProviderRequest.enabled:type_name -> uniedit.common.v1.BoolValue
	23, // 27: uniedit.ai.v1.Model.options:type_name -> google.protobuf.Struct
	16, // 28: uniedit.ai.v1.ListModelsResponse.models:type_name -> uniedit.ai.v1.Model
	16, // 29: uniedit.ai.v1.ListAllModelsResponse.data:type_name -> uniedit.ai.v1.Model
	23, // 30: uniedit.ai.v1.CreateModelRequest.options:type_name -> google.protobuf.Struct
	24, // 31: uniedit.ai.v1.UpdateModelRequest.name:type_name -> uniedit.common.v1.StringValue
	27, // 32: uniedit.ai.v1.UpdateModelRequest.capabilities:type_name -> uniedit.common.v1.StringList
	25, // 33: uniedit.ai.v1.UpdateModelRequest.context_window:type_name -> uniedit.common.v1.Int32Value
	25, // 34: uniedit.ai.v1.UpdateModelRequest.max_output_tokens:type_name -> uniedit.common.v1.Int32Value
	21, // 35: uniedit.ai.v1.UpdateModelRequest.input_cost_per_1k:type_name -> google.protobuf.DoubleValue
	21, // 36: uniedit.ai.v1.UpdateModelRequest.output_cost_per_1k:type_name -> google.protobuf.DoubleValue
	23, // 37: uniedit.ai.v1.UpdateModelRequest.options:type_name -> google.protobuf.Struct
	26, // 38: uniedit.ai.v1.UpdateModelRequest.enabled:type_name -> uniedit.common.v1.BoolValue
	1,  // 39: uniedit.ai.v1.AIService.Chat:input_type -> uniedit.ai.v1.ChatRequest
	1,  // 40: uniedit.ai.v1.AIService.ChatStream:input_type -> uniedit.ai.v1.ChatRequest
	28, // 41: uniedit.ai.v1.AIService.ListModels:input_type -> uniedit.common.v1.Empty
	0,  // 42: uniedit.ai.v1.AIService.GetModel:input_type -> uniedit.ai.v1.GetByIDRequest
	28, // 43: uniedit.ai.v1.AIAdminService.ListProviders:input_type -> uniedit.common.v1.Empty
	13, // 44: uniedit.ai.v1.AIAdminService.CreateProvider:input_type -> uniedit.ai.v1.CreateProviderRequest
	0,  // 45: uniedit.ai.v1.AIAdminService.GetProvider:input_type -> uniedit.ai.v1.GetByIDRequest
	14, // 46: uniedit.ai.v1.AIAdminService.UpdateProvider:input_type -> uniedit.ai.v1.UpdateProviderRequest
	0,  // 47: uniedit.ai.v1.AIAdminService.DeleteProvider:input_type -> uniedit.ai.v1.GetByIDRequest
	0,  // 48: uniedit.ai.v1.AIAdminService.SyncModels:input_type -> uniedit.ai.v1.GetByIDRequest
	0,  // 49: uniedit.ai.v1.AIAdminService.HealthCheck:input_type -> uniedit.ai.v1.GetByIDRequest
	28, // 50: uniedit.ai.v1.AIAdminService.ListAllModels:input_type -> uniedit.common.v1.Empty
	19, // 51: uniedit.ai.v1.AIAdminService.CreateModel:input_type -> uniedit.ai.v1.CreateModelRequest
	0,  // 52: uniedit.ai.v1.AIAdminService.GetAdminModel:input_type -> uniedit.ai.v1.GetByIDRequest
	20, // 53: uniedit.ai.v1.AIAdminService.UpdateModel:input_type -> uniedit.ai.v1.UpdateModelRequest
	0,  // 54: uniedit.ai.v1.AIAdminService.DeleteModel:input_type -> uniedit.ai.v1.GetByIDRequest
	9,  // 55: uniedit.ai.v1.AIService.Chat:output_type -> uniedit.ai.v1.ChatResponse
	28, // 56: uniedit.ai.v1.AIService.ChatStream:output_type -> uniedit.common.v1.Empty
	17, // 57: uniedit.ai.v1.AIService.ListModels:output_type -> uniedit.ai.v1.ListModelsResponse
	16, // 58: uniedit.ai.v1.AIService.GetModel:output_type -> uniedit.ai.v1.Model
	12, // 59: uniedit.ai.v1.AIAdminService.ListProviders:output_type -> uniedit.ai.v1.ListProvidersResponse
	11, // 60: uniedit.ai.v1.AIAdminService.CreateProvider:output_type -> uniedit.ai.v1.Provider
	11, // 61: uniedit.ai.v1.AIAdminService.GetProvider:output_type -> uniedit.ai.v1.Provider
	11, // 62: uniedit.ai.v1.AIAdminService.UpdateProvider:output_type -> uniedit.ai.v1.Provider
	29, // 63: uniedit.ai.v1.AIAdminService.DeleteProvider:output_type -> uniedit.common.v1.MessageResponse
	29, // 64: uniedit.ai.v1.AIAdminService.SyncModels:output_type -> uniedit.common.v1.MessageResponse
	15, // 65: uniedit.ai.v1.AIAdminService.HealthCheck:output_type -> uniedit.ai.v1.HealthCheckResponse
	18, // 66: uniedit.ai.v1.AIAdminService.ListAllModels:output_type -> uniedit.ai.v1.ListAllModelsResponse
	16, // 67: uniedit.ai.v1.AIAdminService.CreateModel:output_type -> uniedit.ai.v1.Model
	16, // 68: uniedit.ai.v1.AIAdminService.GetAdminModel:output_type -> uniedit.ai.v1.Model
	16, // 69: uniedit.ai.v1.AIAdminService.UpdateModel:output_type -> uniedit.ai.v1.Model
	29, // 70: uniedit.ai.v1.AIAdminService.DeleteModel:output_type -> uniedit.common.v1.MessageResponse
	55, // [55:71] is the sub-list for method output_type
	39, // [39:55] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_ai_ai_proto_init() }
func file_ai_ai_proto_init() {
	if File_ai_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_ai_proto_rawDesc), len(file_ai_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ai_ai_proto_goTypes,
		DependencyIndexes: file_ai_ai_proto_depIdxs,
		MessageInfos:      file_ai_ai_proto_msgTypes,
	}.Build()
	File_ai_ai_proto = out.File
	file_ai_ai_proto_goTypes = nil
	file_ai_ai_proto_depIdxs = nil
}
