// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// source: ai/ai.proto

package aiv1

import (
	gin "github.com/gin-gonic/gin"
	common "github.com/uniedit/server/api/pb/common"
	protohttp "github.com/uniedit/server/internal/transport/protohttp"
)

type AIServiceGinServer interface {
	Chat(c *gin.Context, in *ChatRequest) (*ChatResponse, error)
	ChatStream(c *gin.Context, in *ChatRequest) (*common.Empty, error)
	ListModels(c *gin.Context, in *common.Empty) (*ListModelsResponse, error)
	GetModel(c *gin.Context, in *GetByIDRequest) (*Model, error)
}

func RegisterAIServiceGinServer(r gin.IRoutes, srv AIServiceGinServer) {
	r.Handle("POST", "/ai/chat", _AIService_Chat0_Gin_Handler(srv))
	r.Handle("POST", "/ai/chat/stream", _AIService_ChatStream0_Gin_Handler(srv))
	r.Handle("GET", "/ai/models", _AIService_ListModels0_Gin_Handler(srv))
	r.Handle("GET", "/ai/models/:id", _AIService_GetModel0_Gin_Handler(srv))
}

func _AIService_Chat0_Gin_Handler(srv AIServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ChatRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.Chat(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIService_ChatStream0_Gin_Handler(srv AIServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ChatRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ChatStream(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIService_ListModels0_Gin_Handler(srv AIServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in common.Empty
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListModels(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIService_GetModel0_Gin_Handler(srv AIServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetModel(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

type AIAdminServiceGinServer interface {
	ListProviders(c *gin.Context, in *common.Empty) (*ListProvidersResponse, error)
	CreateProvider(c *gin.Context, in *CreateProviderRequest) (*Provider, error)
	GetProvider(c *gin.Context, in *GetByIDRequest) (*Provider, error)
	UpdateProvider(c *gin.Context, in *UpdateProviderRequest) (*Provider, error)
	DeleteProvider(c *gin.Context, in *GetByIDRequest) (*common.MessageResponse, error)
	SyncModels(c *gin.Context, in *GetByIDRequest) (*common.MessageResponse, error)
	HealthCheck(c *gin.Context, in *GetByIDRequest) (*HealthCheckResponse, error)
	ListAllModels(c *gin.Context, in *common.Empty) (*ListAllModelsResponse, error)
	CreateModel(c *gin.Context, in *CreateModelRequest) (*Model, error)
	GetAdminModel(c *gin.Context, in *GetByIDRequest) (*Model, error)
	UpdateModel(c *gin.Context, in *UpdateModelRequest) (*Model, error)
	DeleteModel(c *gin.Context, in *GetByIDRequest) (*common.MessageResponse, error)
}

func RegisterAIAdminServiceGinServer(r gin.IRoutes, srv AIAdminServiceGinServer) {
	r.Handle("GET", "/admin/ai/providers", _AIAdminService_ListProviders0_Gin_Handler(srv))
	r.Handle("POST", "/admin/ai/providers", _AIAdminService_CreateProvider0_Gin_Handler(srv))
	r.Handle("GET", "/admin/ai/providers/:id", _AIAdminService_GetProvider0_Gin_Handler(srv))
	r.Handle("PUT", "/admin/ai/providers/:id", _AIAdminService_UpdateProvider0_Gin_Handler(srv))
	r.Handle("DELETE", "/admin/ai/providers/:id", _AIAdminService_DeleteProvider0_Gin_Handler(srv))
	r.Handle("POST", "/admin/ai/providers/:id/sync", _AIAdminService_SyncModels0_Gin_Handler(srv))
	r.Handle("POST", "/admin/ai/providers/:id/health", _AIAdminService_HealthCheck0_Gin_Handler(srv))
	r.Handle("GET", "/admin/ai/models", _AIAdminService_ListAllModels0_Gin_Handler(srv))
	r.Handle("POST", "/admin/ai/models", _AIAdminService_CreateModel0_Gin_Handler(srv))
	r.Handle("GET", "/admin/ai/models/:id", _AIAdminService_GetAdminModel0_Gin_Handler(srv))
	r.Handle("PUT", "/admin/ai/models/:id", _AIAdminService_UpdateModel0_Gin_Handler(srv))
	r.Handle("DELETE", "/admin/ai/models/:id", _AIAdminService_DeleteModel0_Gin_Handler(srv))
}

func _AIAdminService_ListProviders0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in common.Empty
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListProviders(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIAdminService_CreateProvider0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CreateProviderRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.CreateProvider(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIAdminService_GetProvider0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetProvider(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIAdminService_UpdateProvider0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in UpdateProviderRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.UpdateProvider(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIAdminService_DeleteProvider0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.DeleteProvider(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIAdminService_SyncModels0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.SyncModels(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIAdminService_HealthCheck0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.HealthCheck(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIAdminService_ListAllModels0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in common.Empty
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListAllModels(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIAdminService_CreateModel0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CreateModelRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.CreateModel(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIAdminService_GetAdminModel0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetAdminModel(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIAdminService_UpdateModel0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in UpdateModelRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.UpdateModel(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _AIAdminService_DeleteModel0_Gin_Handler(srv AIAdminServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.DeleteModel(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}
