// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	auth3 "github.com/uniedit/server/internal/app/command/auth"
	"github.com/uniedit/server/internal/app/command/billing"
	"github.com/uniedit/server/internal/app/command/collaboration"
	"github.com/uniedit/server/internal/app/command/order"
	"github.com/uniedit/server/internal/app/command/payment"
	"github.com/uniedit/server/internal/app/command/user"
	auth2 "github.com/uniedit/server/internal/app/query/auth"
	billing2 "github.com/uniedit/server/internal/app/query/billing"
	collaboration2 "github.com/uniedit/server/internal/app/query/collaboration"
	order2 "github.com/uniedit/server/internal/app/query/order"
	payment2 "github.com/uniedit/server/internal/app/query/payment"
	user2 "github.com/uniedit/server/internal/app/query/user"
	"github.com/uniedit/server/internal/domain/auth"
	billing3 "github.com/uniedit/server/internal/domain/billing"
	collaboration3 "github.com/uniedit/server/internal/domain/collaboration"
	"github.com/uniedit/server/internal/domain/git"
	order3 "github.com/uniedit/server/internal/domain/order"
	payment3 "github.com/uniedit/server/internal/domain/payment"
	user3 "github.com/uniedit/server/internal/domain/user"
	"github.com/uniedit/server/internal/infra/persistence"
	"github.com/uniedit/server/internal/ports/http"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeBillingHandlers creates BillingHandlers with all dependencies.
func InitializeBillingHandlers(db *gorm.DB) (*BillingHandlers, error) {
	billingRepository := persistence.NewBillingRepository(db)
	createSubscriptionHandler := billing.NewCreateSubscriptionHandler(billingRepository)
	cancelSubscriptionHandler := billing.NewCancelSubscriptionHandler(billingRepository)
	getSubscriptionHandler := billing2.NewGetSubscriptionHandler(billingRepository)
	listPlansHandler := billing2.NewListPlansHandler(billingRepository)
	getUsageStatsHandler := billing2.NewGetUsageStatsHandler(billingRepository)
	billingHandlers := &BillingHandlers{
		CreateSubscription: createSubscriptionHandler,
		CancelSubscription: cancelSubscriptionHandler,
		GetSubscription:    getSubscriptionHandler,
		ListPlans:          listPlansHandler,
		GetUsageStats:      getUsageStatsHandler,
	}
	return billingHandlers, nil
}

// InitializeOrderHandlers creates OrderHandlers with all dependencies.
func InitializeOrderHandlers(db *gorm.DB) (*OrderHandlers, error) {
	orderRepository := persistence.NewOrderRepository(db)
	createOrderHandler := order.NewCreateOrderHandler(orderRepository)
	cancelOrderHandler := order.NewCancelOrderHandler(orderRepository)
	getOrderHandler := order2.NewGetOrderHandler(orderRepository)
	listOrdersHandler := order2.NewListOrdersHandler(orderRepository)
	orderHandlers := &OrderHandlers{
		CreateOrder: createOrderHandler,
		CancelOrder: cancelOrderHandler,
		GetOrder:    getOrderHandler,
		ListOrders:  listOrdersHandler,
	}
	return orderHandlers, nil
}

// InitializePaymentHandlers creates PaymentHandlers with all dependencies.
func InitializePaymentHandlers(db *gorm.DB) (*PaymentHandlers, error) {
	paymentRepository := persistence.NewPaymentRepository(db)
	createPaymentHandler := payment.NewCreatePaymentHandler(paymentRepository)
	markPaymentSucceededHandler := payment.NewMarkPaymentSucceededHandler(paymentRepository)
	refundPaymentHandler := payment.NewRefundPaymentHandler(paymentRepository)
	getPaymentHandler := payment2.NewGetPaymentHandler(paymentRepository)
	listPaymentsByOrderHandler := payment2.NewListPaymentsByOrderHandler(paymentRepository)
	paymentHandlers := &PaymentHandlers{
		CreatePayment:       createPaymentHandler,
		MarkSucceeded:       markPaymentSucceededHandler,
		RefundPayment:       refundPaymentHandler,
		GetPayment:          getPaymentHandler,
		ListPaymentsByOrder: listPaymentsByOrderHandler,
	}
	return paymentHandlers, nil
}

// InitializeHSTHandlers creates all HTTP handlers with all dependencies.
func InitializeHSTHandlers(db *gorm.DB) (*HSTHandlers, error) {
	billingRepository := persistence.NewBillingRepository(db)
	createSubscriptionHandler := billing.NewCreateSubscriptionHandler(billingRepository)
	cancelSubscriptionHandler := billing.NewCancelSubscriptionHandler(billingRepository)
	getSubscriptionHandler := billing2.NewGetSubscriptionHandler(billingRepository)
	listPlansHandler := billing2.NewListPlansHandler(billingRepository)
	getUsageStatsHandler := billing2.NewGetUsageStatsHandler(billingRepository)
	billingHandler := http.NewBillingHandler(createSubscriptionHandler, cancelSubscriptionHandler, getSubscriptionHandler, listPlansHandler, getUsageStatsHandler)
	orderRepository := persistence.NewOrderRepository(db)
	createOrderHandler := order.NewCreateOrderHandler(orderRepository)
	cancelOrderHandler := order.NewCancelOrderHandler(orderRepository)
	getOrderHandler := order2.NewGetOrderHandler(orderRepository)
	listOrdersHandler := order2.NewListOrdersHandler(orderRepository)
	orderHandler := http.NewOrderHandler(createOrderHandler, cancelOrderHandler, getOrderHandler, listOrdersHandler)
	paymentRepository := persistence.NewPaymentRepository(db)
	createPaymentHandler := payment.NewCreatePaymentHandler(paymentRepository)
	markPaymentSucceededHandler := payment.NewMarkPaymentSucceededHandler(paymentRepository)
	refundPaymentHandler := payment.NewRefundPaymentHandler(paymentRepository)
	getPaymentHandler := payment2.NewGetPaymentHandler(paymentRepository)
	listPaymentsByOrderHandler := payment2.NewListPaymentsByOrderHandler(paymentRepository)
	paymentHandler := http.NewPaymentHandler(createPaymentHandler, markPaymentSucceededHandler, refundPaymentHandler, getPaymentHandler, listPaymentsByOrderHandler)
	userRepository := persistence.NewUserRepository(db)
	registerHandler := user.NewRegisterHandler(userRepository)
	verifyEmailHandler := user.NewVerifyEmailHandler(userRepository)
	resendVerificationHandler := user.NewResendVerificationHandler(userRepository)
	requestPasswordResetHandler := user.NewRequestPasswordResetHandler(userRepository)
	resetPasswordHandler := user.NewResetPasswordHandler(userRepository)
	changePasswordHandler := user.NewChangePasswordHandler(userRepository)
	updateProfileHandler := user.NewUpdateProfileHandler(userRepository)
	deleteAccountHandler := user.NewDeleteAccountHandler(userRepository)
	suspendUserHandler := user.NewSuspendUserHandler(userRepository)
	reactivateUserHandler := user.NewReactivateUserHandler(userRepository)
	setAdminStatusHandler := user.NewSetAdminStatusHandler(userRepository)
	getUserHandler := user2.NewGetUserHandler(userRepository)
	getUserByEmailHandler := user2.NewGetUserByEmailHandler(userRepository)
	listUsersHandler := user2.NewListUsersHandler(userRepository)
	userHandler := http.NewUserHandler(registerHandler, verifyEmailHandler, resendVerificationHandler, requestPasswordResetHandler, resetPasswordHandler, changePasswordHandler, updateProfileHandler, deleteAccountHandler, suspendUserHandler, reactivateUserHandler, setAdminStatusHandler, getUserHandler, getUserByEmailHandler, listUsersHandler)
	hstHandlers := &HSTHandlers{
		Billing: billingHandler,
		Order:   orderHandler,
		Payment: paymentHandler,
		User:    userHandler,
	}
	return hstHandlers, nil
}

// InitializeCollaborationHandlers creates CollaborationHandlers with all dependencies.
func InitializeCollaborationHandlers(db *gorm.DB) (*CollaborationHandlers, error) {
	collaborationUnitOfWork := persistence.NewCollaborationUnitOfWork(db)
	teamRepository := persistence.NewTeamRepository(db)
	createTeamHandler := collaboration.NewCreateTeamHandler(collaborationUnitOfWork, teamRepository)
	memberRepository := persistence.NewMemberRepository(db)
	updateTeamHandler := collaboration.NewUpdateTeamHandler(teamRepository, memberRepository)
	deleteTeamHandler := collaboration.NewDeleteTeamHandler(collaborationUnitOfWork, memberRepository)
	invitationRepository := persistence.NewInvitationRepository(db)
	userRepository := persistence.NewUserRepository(db)
	userLookupAdapter := persistence.NewUserLookupAdapter(userRepository)
	sendInvitationHandler := collaboration.NewSendInvitationHandler(teamRepository, memberRepository, invitationRepository, userLookupAdapter)
	acceptInvitationHandler := collaboration.NewAcceptInvitationHandler(collaborationUnitOfWork, invitationRepository, teamRepository)
	rejectInvitationHandler := collaboration.NewRejectInvitationHandler(invitationRepository)
	revokeInvitationHandler := collaboration.NewRevokeInvitationHandler(invitationRepository, memberRepository)
	updateMemberRoleHandler := collaboration.NewUpdateMemberRoleHandler(memberRepository)
	removeMemberHandler := collaboration.NewRemoveMemberHandler(memberRepository)
	leaveTeamHandler := collaboration.NewLeaveTeamHandler(memberRepository)
	getTeamHandler := collaboration2.NewGetTeamHandler(teamRepository, memberRepository)
	listMyTeamsHandler := collaboration2.NewListMyTeamsHandler(teamRepository)
	listMembersHandler := collaboration2.NewListMembersHandler(memberRepository)
	listInvitationsHandler := collaboration2.NewListInvitationsHandler(memberRepository, invitationRepository)
	listMyInvitationsHandler := collaboration2.NewListMyInvitationsHandler(invitationRepository)
	collaborationHandlers := &CollaborationHandlers{
		CreateTeam:        createTeamHandler,
		UpdateTeam:        updateTeamHandler,
		DeleteTeam:        deleteTeamHandler,
		SendInvitation:    sendInvitationHandler,
		AcceptInvitation:  acceptInvitationHandler,
		RejectInvitation:  rejectInvitationHandler,
		RevokeInvitation:  revokeInvitationHandler,
		UpdateMemberRole:  updateMemberRoleHandler,
		RemoveMember:      removeMemberHandler,
		LeaveTeam:         leaveTeamHandler,
		GetTeam:           getTeamHandler,
		ListMyTeams:       listMyTeamsHandler,
		ListMembers:       listMembersHandler,
		ListInvitations:   listInvitationsHandler,
		ListMyInvitations: listMyInvitationsHandler,
	}
	return collaborationHandlers, nil
}

// wire.go:

// RepositorySet provides all repository implementations.
var RepositorySet = wire.NewSet(persistence.NewBillingRepository, wire.Bind(new(billing3.Repository), new(*persistence.BillingRepository)), persistence.NewOrderRepository, wire.Bind(new(order3.Repository), new(*persistence.OrderRepository)), persistence.NewPaymentRepository, wire.Bind(new(payment3.Repository), new(*persistence.PaymentRepository)), persistence.NewUserRepository, wire.Bind(new(user3.Repository), new(*persistence.UserRepository)), persistence.NewRefreshTokenRepository, wire.Bind(new(auth.RefreshTokenRepository), new(*persistence.RefreshTokenRepository)), persistence.NewUserAPIKeyRepository, wire.Bind(new(auth.UserAPIKeyRepository), new(*persistence.UserAPIKeyRepository)), persistence.NewSystemAPIKeyRepository, wire.Bind(new(auth.SystemAPIKeyRepository), new(*persistence.SystemAPIKeyRepository)), persistence.NewCollaborationUnitOfWork, wire.Bind(new(collaboration3.UnitOfWork), new(*persistence.CollaborationUnitOfWork)), persistence.NewTeamRepository, wire.Bind(new(collaboration3.TeamRepository), new(*persistence.TeamRepository)), persistence.NewMemberRepository, wire.Bind(new(collaboration3.MemberRepository), new(*persistence.MemberRepository)), persistence.NewInvitationRepository, wire.Bind(new(collaboration3.InvitationRepository), new(*persistence.InvitationRepository)), persistence.NewUserLookupAdapter, wire.Bind(new(collaboration3.UserLookup), new(*persistence.UserLookupAdapter)), persistence.NewGitRepositoryRepository, wire.Bind(new(git.RepositoryRepository), new(*persistence.GitRepositoryRepository)), persistence.NewGitCollaboratorRepository, wire.Bind(new(git.CollaboratorRepository), new(*persistence.GitCollaboratorRepository)), persistence.NewGitPullRequestRepository, wire.Bind(new(git.PullRequestRepository), new(*persistence.GitPullRequestRepository)), persistence.NewGitLFSRepository, wire.Bind(new(git.LFSRepository), new(*persistence.GitLFSRepository)))

// BillingCommandSet provides billing command handlers.
var BillingCommandSet = wire.NewSet(billing.NewCreateSubscriptionHandler, billing.NewCancelSubscriptionHandler)

// BillingQuerySet provides billing query handlers.
var BillingQuerySet = wire.NewSet(billing2.NewGetSubscriptionHandler, billing2.NewListPlansHandler, billing2.NewGetUsageStatsHandler)

// OrderCommandSet provides order command handlers.
var OrderCommandSet = wire.NewSet(order.NewCreateOrderHandler, order.NewCancelOrderHandler)

// OrderQuerySet provides order query handlers.
var OrderQuerySet = wire.NewSet(order2.NewGetOrderHandler, order2.NewListOrdersHandler)

// PaymentCommandSet provides payment command handlers.
var PaymentCommandSet = wire.NewSet(payment.NewCreatePaymentHandler, payment.NewMarkPaymentSucceededHandler, payment.NewRefundPaymentHandler)

// PaymentQuerySet provides payment query handlers.
var PaymentQuerySet = wire.NewSet(payment2.NewGetPaymentHandler, payment2.NewListPaymentsByOrderHandler)

// UserCommandSet provides user command handlers.
var UserCommandSet = wire.NewSet(user.NewRegisterHandler, user.NewVerifyEmailHandler, user.NewResendVerificationHandler, user.NewRequestPasswordResetHandler, user.NewResetPasswordHandler, user.NewChangePasswordHandler, user.NewUpdateProfileHandler, user.NewDeleteAccountHandler, user.NewSuspendUserHandler, user.NewReactivateUserHandler, user.NewSetAdminStatusHandler)

// UserQuerySet provides user query handlers.
var UserQuerySet = wire.NewSet(user2.NewGetUserHandler, user2.NewGetUserByEmailHandler, user2.NewListUsersHandler)

// AuthQuerySet provides auth query handlers.
var AuthQuerySet = wire.NewSet(auth2.NewListUserAPIKeysHandler, auth2.NewListSystemAPIKeysHandler, auth2.NewGetSystemAPIKeyHandler)

// CollaborationCommandSet provides collaboration command handlers.
var CollaborationCommandSet = wire.NewSet(collaboration.NewCreateTeamHandler, collaboration.NewUpdateTeamHandler, collaboration.NewDeleteTeamHandler, collaboration.NewSendInvitationHandler, collaboration.NewAcceptInvitationHandler, collaboration.NewRejectInvitationHandler, collaboration.NewRevokeInvitationHandler, collaboration.NewUpdateMemberRoleHandler, collaboration.NewRemoveMemberHandler, collaboration.NewLeaveTeamHandler)

// CollaborationQuerySet provides collaboration query handlers.
var CollaborationQuerySet = wire.NewSet(collaboration2.NewGetTeamHandler, collaboration2.NewListMyTeamsHandler, collaboration2.NewListMembersHandler, collaboration2.NewListInvitationsHandler, collaboration2.NewListMyInvitationsHandler)

// HTTPHandlerSet provides HTTP handlers.
var HTTPHandlerSet = wire.NewSet(http.NewBillingHandler, http.NewOrderHandler, http.NewPaymentHandler, http.NewUserHandler)

// HSTSet combines all HST layer providers.
var HSTSet = wire.NewSet(
	RepositorySet,
	BillingCommandSet,
	BillingQuerySet,
	OrderCommandSet,
	OrderQuerySet,
	PaymentCommandSet,
	PaymentQuerySet,
	UserCommandSet,
	UserQuerySet,
	AuthQuerySet,
	CollaborationCommandSet,
	CollaborationQuerySet,
	HTTPHandlerSet,
)

// BillingHandlers contains all billing command and query handlers.
type BillingHandlers struct {
	CreateSubscription *billing.CreateSubscriptionHandler
	CancelSubscription *billing.CancelSubscriptionHandler
	GetSubscription    *billing2.GetSubscriptionHandler
	ListPlans          *billing2.ListPlansHandler
	GetUsageStats      *billing2.GetUsageStatsHandler
}

// OrderHandlers contains all order command and query handlers.
type OrderHandlers struct {
	CreateOrder *order.CreateOrderHandler
	CancelOrder *order.CancelOrderHandler
	GetOrder    *order2.GetOrderHandler
	ListOrders  *order2.ListOrdersHandler
}

// PaymentHandlers contains all payment command and query handlers.
type PaymentHandlers struct {
	CreatePayment       *payment.CreatePaymentHandler
	MarkSucceeded       *payment.MarkPaymentSucceededHandler
	RefundPayment       *payment.RefundPaymentHandler
	GetPayment          *payment2.GetPaymentHandler
	ListPaymentsByOrder *payment2.ListPaymentsByOrderHandler
}

// HSTHandlers contains all HTTP handlers for the HST architecture.
type HSTHandlers struct {
	Billing *http.BillingHandler
	Order   *http.OrderHandler
	Payment *http.PaymentHandler
	User    *http.UserHandler
}

// AuthHandlers contains all auth command and query handlers.
// Note: AuthHandler requires external dependencies that must be provided separately:
// - OAuthRegistry: OAuth provider registry
// - OAuthStateStore: OAuth state storage (typically Redis)
// - JWTGenerator: JWT token generator
// - CryptoManager: Encryption/decryption manager
// - TokenValidator: Access token validator
type AuthHandlers struct {
	// Token Commands
	RefreshTokens *auth3.RefreshTokensHandler
	Logout        *auth3.LogoutHandler

	// User API Key Commands
	CreateUserAPIKey *auth3.CreateUserAPIKeyHandler
	DeleteUserAPIKey *auth3.DeleteUserAPIKeyHandler
	RotateUserAPIKey *auth3.RotateUserAPIKeyHandler

	// System API Key Commands
	CreateSystemAPIKey   *auth3.CreateSystemAPIKeyHandler
	UpdateSystemAPIKey   *auth3.UpdateSystemAPIKeyHandler
	DeleteSystemAPIKey   *auth3.DeleteSystemAPIKeyHandler
	RotateSystemAPIKey   *auth3.RotateSystemAPIKeyHandler
	ValidateSystemAPIKey *auth3.ValidateSystemAPIKeyHandler

	// Queries
	ListUserAPIKeys   *auth2.ListUserAPIKeysHandler
	ListSystemAPIKeys *auth2.ListSystemAPIKeysHandler
	GetSystemAPIKey   *auth2.GetSystemAPIKeyHandler
}

// CollaborationHandlers contains all collaboration command and query handlers.
type CollaborationHandlers struct {
	// Team Commands
	CreateTeam *collaboration.CreateTeamHandler
	UpdateTeam *collaboration.UpdateTeamHandler
	DeleteTeam *collaboration.DeleteTeamHandler

	// Invitation Commands
	SendInvitation   *collaboration.SendInvitationHandler
	AcceptInvitation *collaboration.AcceptInvitationHandler
	RejectInvitation *collaboration.RejectInvitationHandler
	RevokeInvitation *collaboration.RevokeInvitationHandler

	// Member Commands
	UpdateMemberRole *collaboration.UpdateMemberRoleHandler
	RemoveMember     *collaboration.RemoveMemberHandler
	LeaveTeam        *collaboration.LeaveTeamHandler

	// Queries
	GetTeam           *collaboration2.GetTeamHandler
	ListMyTeams       *collaboration2.ListMyTeamsHandler
	ListMembers       *collaboration2.ListMembersHandler
	ListInvitations   *collaboration2.ListInvitationsHandler
	ListMyInvitations *collaboration2.ListMyInvitationsHandler
}
