// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: media/media.proto

package mediav1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	common "github.com/uniedit/server/api/pb/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_media_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetByTaskIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByTaskIDRequest) Reset() {
	*x = GetByTaskIDRequest{}
	mi := &file_media_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByTaskIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByTaskIDRequest) ProtoMessage() {}

func (x *GetByTaskIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByTaskIDRequest.ProtoReflect.Descriptor instead.
func (*GetByTaskIDRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{1}
}

func (x *GetByTaskIDRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GenerateImageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prompt         string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	NegativePrompt string                 `protobuf:"bytes,2,opt,name=negative_prompt,json=negativePrompt,proto3" json:"negative_prompt,omitempty"`
	N              int32                  `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`
	Size           string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Quality        string                 `protobuf:"bytes,5,opt,name=quality,proto3" json:"quality,omitempty"`
	Style          string                 `protobuf:"bytes,6,opt,name=style,proto3" json:"style,omitempty"`
	Model          string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	ResponseFormat string                 `protobuf:"bytes,8,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateImageRequest) Reset() {
	*x = GenerateImageRequest{}
	mi := &file_media_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageRequest) ProtoMessage() {}

func (x *GenerateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageRequest.ProtoReflect.Descriptor instead.
func (*GenerateImageRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateImageRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateImageRequest) GetNegativePrompt() string {
	if x != nil {
		return x.NegativePrompt
	}
	return ""
}

func (x *GenerateImageRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *GenerateImageRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *GenerateImageRequest) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *GenerateImageRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *GenerateImageRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateImageRequest) GetResponseFormat() string {
	if x != nil {
		return x.ResponseFormat
	}
	return ""
}

type GeneratedImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	B64Json       string                 `protobuf:"bytes,2,opt,name=b64_json,json=b64Json,proto3" json:"b64_json,omitempty"`
	RevisedPrompt string                 `protobuf:"bytes,3,opt,name=revised_prompt,json=revisedPrompt,proto3" json:"revised_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedImage) Reset() {
	*x = GeneratedImage{}
	mi := &file_media_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedImage) ProtoMessage() {}

func (x *GeneratedImage) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedImage.ProtoReflect.Descriptor instead.
func (*GeneratedImage) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{3}
}

func (x *GeneratedImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GeneratedImage) GetB64Json() string {
	if x != nil {
		return x.B64Json
	}
	return ""
}

func (x *GeneratedImage) GetRevisedPrompt() string {
	if x != nil {
		return x.RevisedPrompt
	}
	return ""
}

type ImageUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalImages   int32                  `protobuf:"varint,1,opt,name=total_images,json=totalImages,proto3" json:"total_images,omitempty"`
	CostUsd       float64                `protobuf:"fixed64,2,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUsage) Reset() {
	*x = ImageUsage{}
	mi := &file_media_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUsage) ProtoMessage() {}

func (x *ImageUsage) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUsage.ProtoReflect.Descriptor instead.
func (*ImageUsage) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{4}
}

func (x *ImageUsage) GetTotalImages() int32 {
	if x != nil {
		return x.TotalImages
	}
	return 0
}

func (x *ImageUsage) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

type GenerateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*GeneratedImage      `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Usage         *ImageUsage            `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TaskId        string                 `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImageResponse) Reset() {
	*x = GenerateImageResponse{}
	mi := &file_media_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageResponse) ProtoMessage() {}

func (x *GenerateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageResponse.ProtoReflect.Descriptor instead.
func (*GenerateImageResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateImageResponse) GetImages() []*GeneratedImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GenerateImageResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateImageResponse) GetUsage() *ImageUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *GenerateImageResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GenerateImageResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GenerateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	InputImage    string                 `protobuf:"bytes,2,opt,name=input_image,json=inputImage,proto3" json:"input_image,omitempty"`
	InputVideo    string                 `protobuf:"bytes,3,opt,name=input_video,json=inputVideo,proto3" json:"input_video,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	AspectRatio   string                 `protobuf:"bytes,5,opt,name=aspect_ratio,json=aspectRatio,proto3" json:"aspect_ratio,omitempty"`
	Resolution    string                 `protobuf:"bytes,6,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Fps           int32                  `protobuf:"varint,7,opt,name=fps,proto3" json:"fps,omitempty"`
	Model         string                 `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateVideoRequest) Reset() {
	*x = GenerateVideoRequest{}
	mi := &file_media_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateVideoRequest) ProtoMessage() {}

func (x *GenerateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateVideoRequest.ProtoReflect.Descriptor instead.
func (*GenerateVideoRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateVideoRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateVideoRequest) GetInputImage() string {
	if x != nil {
		return x.InputImage
	}
	return ""
}

func (x *GenerateVideoRequest) GetInputVideo() string {
	if x != nil {
		return x.InputVideo
	}
	return ""
}

func (x *GenerateVideoRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *GenerateVideoRequest) GetAspectRatio() string {
	if x != nil {
		return x.AspectRatio
	}
	return ""
}

func (x *GenerateVideoRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *GenerateVideoRequest) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *GenerateVideoRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type GeneratedVideo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Duration      int32                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Fps           int32                  `protobuf:"varint,5,opt,name=fps,proto3" json:"fps,omitempty"`
	FileSize      int64                  `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Format        string                 `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedVideo) Reset() {
	*x = GeneratedVideo{}
	mi := &file_media_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedVideo) ProtoMessage() {}

func (x *GeneratedVideo) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedVideo.ProtoReflect.Descriptor instead.
func (*GeneratedVideo) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{7}
}

func (x *GeneratedVideo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GeneratedVideo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *GeneratedVideo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GeneratedVideo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GeneratedVideo) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *GeneratedVideo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *GeneratedVideo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type VideoGenerationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Video         *GeneratedVideo        `protobuf:"bytes,4,opt,name=video,proto3" json:"video,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoGenerationStatus) Reset() {
	*x = VideoGenerationStatus{}
	mi := &file_media_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoGenerationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoGenerationStatus) ProtoMessage() {}

func (x *VideoGenerationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoGenerationStatus.ProtoReflect.Descriptor instead.
func (*VideoGenerationStatus) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{8}
}

func (x *VideoGenerationStatus) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *VideoGenerationStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoGenerationStatus) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *VideoGenerationStatus) GetVideo() *GeneratedVideo {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *VideoGenerationStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *VideoGenerationStatus) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type MediaTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaTask) Reset() {
	*x = MediaTask{}
	mi := &file_media_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaTask) ProtoMessage() {}

func (x *MediaTask) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaTask.ProtoReflect.Descriptor instead.
func (*MediaTask) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{9}
}

func (x *MediaTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaTask) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *MediaTask) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MediaTask) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *MediaTask) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MediaTask) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MediaTask) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_media_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{10}
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*MediaTask           `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_media_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{11}
}

func (x *ListTasksResponse) GetTasks() []*MediaTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type MediaProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaProvider) Reset() {
	*x = MediaProvider{}
	mi := &file_media_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaProvider) ProtoMessage() {}

func (x *MediaProvider) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaProvider.ProtoReflect.Descriptor instead.
func (*MediaProvider) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{12}
}

func (x *MediaProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MediaProvider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaProvider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *MediaProvider) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MediaProvider) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MediaProvider) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*MediaProvider       `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_media_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{13}
}

func (x *ListProvidersResponse) GetProviders() []*MediaProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type MediaModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId    string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaModel) Reset() {
	*x = MediaModel{}
	mi := &file_media_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaModel) ProtoMessage() {}

func (x *MediaModel) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaModel.ProtoReflect.Descriptor instead.
func (*MediaModel) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{14}
}

func (x *MediaModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaModel) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *MediaModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MediaModel) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *MediaModel) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MediaModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MediaModel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_media_media_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{15}
}

func (x *ListModelsRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*MediaModel          `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_media_media_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{16}
}

func (x *ListModelsResponse) GetModels() []*MediaModel {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_media_media_proto protoreflect.FileDescriptor

const file_media_media_proto_rawDesc = "" +
	"\n" +
	"\x11media/media.proto\x12\x10uniedit.media.v1\x1a\x13common/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x12GetByTaskIDRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xe8\x01\n" +
	"\x14GenerateImageRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12'\n" +
	"\x0fnegative_prompt\x18\x02 \x01(\tR\x0enegativePrompt\x12\f\n" +
	"\x01n\x18\x03 \x01(\x05R\x01n\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\x12\x18\n" +
	"\aquality\x18\x05 \x01(\tR\aquality\x12\x14\n" +
	"\x05style\x18\x06 \x01(\tR\x05style\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12'\n" +
	"\x0fresponse_format\x18\b \x01(\tR\x0eresponseFormat\"d\n" +
	"\x0eGeneratedImage\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\bb64_json\x18\x02 \x01(\tR\ab64Json\x12%\n" +
	"\x0erevised_prompt\x18\x03 \x01(\tR\rrevisedPrompt\"J\n" +
	"\n" +
	"ImageUsage\x12!\n" +
	"\ftotal_images\x18\x01 \x01(\x05R\vtotalImages\x12\x19\n" +
	"\bcost_usd\x18\x02 \x01(\x01R\acostUsd\"\xd3\x01\n" +
	"\x15GenerateImageResponse\x128\n" +
	"\x06images\x18\x01 \x03(\v2 .uniedit.media.v1.GeneratedImageR\x06images\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x122\n" +
	"\x05usage\x18\x03 \x01(\v2\x1c.uniedit.media.v1.ImageUsageR\x05usage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\tR\x06taskId\"\xf7\x01\n" +
	"\x14GenerateVideoRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1f\n" +
	"\vinput_image\x18\x02 \x01(\tR\n" +
	"inputImage\x12\x1f\n" +
	"\vinput_video\x18\x03 \x01(\tR\n" +
	"inputVideo\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12!\n" +
	"\faspect_ratio\x18\x05 \x01(\tR\vaspectRatio\x12\x1e\n" +
	"\n" +
	"resolution\x18\x06 \x01(\tR\n" +
	"resolution\x12\x10\n" +
	"\x03fps\x18\a \x01(\x05R\x03fps\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\"\xb3\x01\n" +
	"\x0eGeneratedVideo\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x10\n" +
	"\x03fps\x18\x05 \x01(\x05R\x03fps\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\x03R\bfileSize\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\"\xd1\x01\n" +
	"\x15VideoGenerationStatus\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x126\n" +
	"\x05video\x18\x04 \x01(\v2 .uniedit.media.v1.GeneratedVideoR\x05video\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\xd2\x01\n" +
	"\tMediaTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x05R\bprogress\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"@\n" +
	"\x10ListTasksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"F\n" +
	"\x11ListTasksResponse\x121\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1b.uniedit.media.v1.MediaTaskR\x05tasks\"\xba\x01\n" +
	"\rMediaProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"V\n" +
	"\x15ListProvidersResponse\x12=\n" +
	"\tproviders\x18\x01 \x03(\v2\x1f.uniedit.media.v1.MediaProviderR\tproviders\"\xcd\x01\n" +
	"\n" +
	"MediaModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"3\n" +
	"\x11ListModelsRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\"J\n" +
	"\x12ListModelsResponse\x124\n" +
	"\x06models\x18\x01 \x03(\v2\x1c.uniedit.media.v1.MediaModelR\x06models2\xf7\x05\n" +
	"\fMediaService\x12\x86\x01\n" +
	"\rGenerateImage\x12&.uniedit.media.v1.GenerateImageRequest\x1a'.uniedit.media.v1.GenerateImageResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/media/images/generations\x12\x86\x01\n" +
	"\rGenerateVideo\x12&.uniedit.media.v1.GenerateVideoRequest\x1a'.uniedit.media.v1.VideoGenerationStatus\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/media/videos/generations\x12\x8c\x01\n" +
	"\x0eGetVideoStatus\x12$.uniedit.media.v1.GetByTaskIDRequest\x1a'.uniedit.media.v1.VideoGenerationStatus\"+\x82\xd3\xe4\x93\x02%\x12#/media/videos/generations/{task_id}\x12j\n" +
	"\tListTasks\x12\".uniedit.media.v1.ListTasksRequest\x1a#.uniedit.media.v1.ListTasksResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/media/tasks\x12l\n" +
	"\aGetTask\x12$.uniedit.media.v1.GetByTaskIDRequest\x1a\x1b.uniedit.media.v1.MediaTask\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/media/tasks/{task_id}\x12l\n" +
	"\n" +
	"CancelTask\x12$.uniedit.media.v1.GetByTaskIDRequest\x1a\x18.uniedit.common.v1.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/media/tasks/{task_id}2\xe2\x02\n" +
	"\x11MediaAdminService\x12l\n" +
	"\rListProviders\x12\x18.uniedit.common.v1.Empty\x1a'.uniedit.media.v1.ListProvidersResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/media/providers\x12o\n" +
	"\vGetProvider\x12 .uniedit.media.v1.GetByIDRequest\x1a\x1f.uniedit.media.v1.MediaProvider\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/media/providers/{id}\x12n\n" +
	"\n" +
	"ListModels\x12#.uniedit.media.v1.ListModelsRequest\x1a$.uniedit.media.v1.ListModelsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/media/modelsB\x9a\x01\x92Ag\x12I\n" +
	"\vUniEdit API\x126UniEdit 后端 API（由 proto 自动生成 OpenAPI）2\x02v1\x1a\x0elocalhost:8080\"\a/api/v1*\x01\x01Z.github.com/uniedit/server/api/pb/media;mediav1b\x06proto3"

var (
	file_media_media_proto_rawDescOnce sync.Once
	file_media_media_proto_rawDescData []byte
)

func file_media_media_proto_rawDescGZIP() []byte {
	file_media_media_proto_rawDescOnce.Do(func() {
		file_media_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_media_proto_rawDesc), len(file_media_media_proto_rawDesc)))
	})
	return file_media_media_proto_rawDescData
}

var file_media_media_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_media_media_proto_goTypes = []any{
	(*GetByIDRequest)(nil),        // 0: uniedit.media.v1.GetByIDRequest
	(*GetByTaskIDRequest)(nil),    // 1: uniedit.media.v1.GetByTaskIDRequest
	(*GenerateImageRequest)(nil),  // 2: uniedit.media.v1.GenerateImageRequest
	(*GeneratedImage)(nil),        // 3: uniedit.media.v1.GeneratedImage
	(*ImageUsage)(nil),            // 4: uniedit.media.v1.ImageUsage
	(*GenerateImageResponse)(nil), // 5: uniedit.media.v1.GenerateImageResponse
	(*GenerateVideoRequest)(nil),  // 6: uniedit.media.v1.GenerateVideoRequest
	(*GeneratedVideo)(nil),        // 7: uniedit.media.v1.GeneratedVideo
	(*VideoGenerationStatus)(nil), // 8: uniedit.media.v1.VideoGenerationStatus
	(*MediaTask)(nil),             // 9: uniedit.media.v1.MediaTask
	(*ListTasksRequest)(nil),      // 10: uniedit.media.v1.ListTasksRequest
	(*ListTasksResponse)(nil),     // 11: uniedit.media.v1.ListTasksResponse
	(*MediaProvider)(nil),         // 12: uniedit.media.v1.MediaProvider
	(*ListProvidersResponse)(nil), // 13: uniedit.media.v1.ListProvidersResponse
	(*MediaModel)(nil),            // 14: uniedit.media.v1.MediaModel
	(*ListModelsRequest)(nil),     // 15: uniedit.media.v1.ListModelsRequest
	(*ListModelsResponse)(nil),    // 16: uniedit.media.v1.ListModelsResponse
	(*common.Empty)(nil),          // 17: uniedit.common.v1.Empty
}
var file_media_media_proto_depIdxs = []int32{
	3,  // 0: uniedit.media.v1.GenerateImageResponse.images:type_name -> uniedit.media.v1.GeneratedImage
	4,  // 1: uniedit.media.v1.GenerateImageResponse.usage:type_name -> uniedit.media.v1.ImageUsage
	7,  // 2: uniedit.media.v1.VideoGenerationStatus.video:type_name -> uniedit.media.v1.GeneratedVideo
	9,  // 3: uniedit.media.v1.ListTasksResponse.tasks:type_name -> uniedit.media.v1.MediaTask
	12, // 4: uniedit.media.v1.ListProvidersResponse.providers:type_name -> uniedit.media.v1.MediaProvider
	14, // 5: uniedit.media.v1.ListModelsResponse.models:type_name -> uniedit.media.v1.MediaModel
	2,  // 6: uniedit.media.v1.MediaService.GenerateImage:input_type -> uniedit.media.v1.GenerateImageRequest
	6,  // 7: uniedit.media.v1.MediaService.GenerateVideo:input_type -> uniedit.media.v1.GenerateVideoRequest
	1,  // 8: uniedit.media.v1.MediaService.GetVideoStatus:input_type -> uniedit.media.v1.GetByTaskIDRequest
	10, // 9: uniedit.media.v1.MediaService.ListTasks:input_type -> uniedit.media.v1.ListTasksRequest
	1,  // 10: uniedit.media.v1.MediaService.GetTask:input_type -> uniedit.media.v1.GetByTaskIDRequest
	1,  // 11: uniedit.media.v1.MediaService.CancelTask:input_type -> uniedit.media.v1.GetByTaskIDRequest
	17, // 12: uniedit.media.v1.MediaAdminService.ListProviders:input_type -> uniedit.common.v1.Empty
	0,  // 13: uniedit.media.v1.MediaAdminService.GetProvider:input_type -> uniedit.media.v1.GetByIDRequest
	15, // 14: uniedit.media.v1.MediaAdminService.ListModels:input_type -> uniedit.media.v1.ListModelsRequest
	5,  // 15: uniedit.media.v1.MediaService.GenerateImage:output_type -> uniedit.media.v1.GenerateImageResponse
	8,  // 16: uniedit.media.v1.MediaService.GenerateVideo:output_type -> uniedit.media.v1.VideoGenerationStatus
	8,  // 17: uniedit.media.v1.MediaService.GetVideoStatus:output_type -> uniedit.media.v1.VideoGenerationStatus
	11, // 18: uniedit.media.v1.MediaService.ListTasks:output_type -> uniedit.media.v1.ListTasksResponse
	9,  // 19: uniedit.media.v1.MediaService.GetTask:output_type -> uniedit.media.v1.MediaTask
	17, // 20: uniedit.media.v1.MediaService.CancelTask:output_type -> uniedit.common.v1.Empty
	13, // 21: uniedit.media.v1.MediaAdminService.ListProviders:output_type -> uniedit.media.v1.ListProvidersResponse
	12, // 22: uniedit.media.v1.MediaAdminService.GetProvider:output_type -> uniedit.media.v1.MediaProvider
	16, // 23: uniedit.media.v1.MediaAdminService.ListModels:output_type -> uniedit.media.v1.ListModelsResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_media_media_proto_init() }
func file_media_media_proto_init() {
	if File_media_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_media_proto_rawDesc), len(file_media_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_media_media_proto_goTypes,
		DependencyIndexes: file_media_media_proto_depIdxs,
		MessageInfos:      file_media_media_proto_msgTypes,
	}.Build()
	File_media_media_proto = out.File
	file_media_media_proto_goTypes = nil
	file_media_media_proto_depIdxs = nil
}
