// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// source: order/order.proto

package orderv1

import (
	gin "github.com/gin-gonic/gin"
	common "github.com/uniedit/server/api/pb/common"
	protohttp "github.com/uniedit/server/internal/transport/protohttp"
)

type OrderServiceGinServer interface {
	CreateSubscriptionOrder(c *gin.Context, in *CreateSubscriptionOrderRequest) (*Order, error)
	CreateTopupOrder(c *gin.Context, in *CreateTopupOrderRequest) (*Order, error)
	ListOrders(c *gin.Context, in *ListOrdersRequest) (*OrderListResponse, error)
	GetOrder(c *gin.Context, in *GetByIDRequest) (*Order, error)
	CancelOrder(c *gin.Context, in *CancelOrderRequest) (*common.MessageResponse, error)
	ListInvoices(c *gin.Context, in *common.Empty) (*InvoiceListResponse, error)
	GetInvoice(c *gin.Context, in *GetByIDRequest) (*Invoice, error)
	DownloadInvoice(c *gin.Context, in *GetByIDRequest) (*DownloadInvoiceResponse, error)
}

func RegisterOrderServiceGinServer(r gin.IRoutes, srv OrderServiceGinServer) {
	r.Handle("POST", "/orders/subscription", _OrderService_CreateSubscriptionOrder0_Gin_Handler(srv))
	r.Handle("POST", "/orders/topup", _OrderService_CreateTopupOrder0_Gin_Handler(srv))
	r.Handle("GET", "/orders", _OrderService_ListOrders0_Gin_Handler(srv))
	r.Handle("GET", "/orders/:id", _OrderService_GetOrder0_Gin_Handler(srv))
	r.Handle("POST", "/orders/:id/cancel", _OrderService_CancelOrder0_Gin_Handler(srv))
	r.Handle("GET", "/invoices", _OrderService_ListInvoices0_Gin_Handler(srv))
	r.Handle("GET", "/invoices/:id", _OrderService_GetInvoice0_Gin_Handler(srv))
	r.Handle("GET", "/invoices/:id/download", _OrderService_DownloadInvoice0_Gin_Handler(srv))
}

func _OrderService_CreateSubscriptionOrder0_Gin_Handler(srv OrderServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CreateSubscriptionOrderRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.CreateSubscriptionOrder(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _OrderService_CreateTopupOrder0_Gin_Handler(srv OrderServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CreateTopupOrderRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.CreateTopupOrder(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _OrderService_ListOrders0_Gin_Handler(srv OrderServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in ListOrdersRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListOrders(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _OrderService_GetOrder0_Gin_Handler(srv OrderServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetOrder(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _OrderService_CancelOrder0_Gin_Handler(srv OrderServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in CancelOrderRequest
		if err := protohttp.BindBody(c, &in, "*"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.CancelOrder(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _OrderService_ListInvoices0_Gin_Handler(srv OrderServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in common.Empty
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.ListInvoices(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _OrderService_GetInvoice0_Gin_Handler(srv OrderServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.GetInvoice(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}

func _OrderService_DownloadInvoice0_Gin_Handler(srv OrderServiceGinServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var in GetByIDRequest
		if err := protohttp.BindQuery(c, &in); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		if err := protohttp.BindVars(c, &in, "id"); err != nil {
			protohttp.AbortBindError(c, err)
			return
		}
		out, err := srv.DownloadInvoice(c, &in)
		if err != nil {
			protohttp.AbortServerError(c, err)
			return
		}
		protohttp.WriteOK(c, out)
	}
}
